== Native Executable

You can build a native image by using GraalVM.
The common use case is creating a Docker image so you can execute the next commands:

[source, bash]
----
./mvnw package -Pnative -Dquarkus.native.container-build=true

docker build -f src/main/docker/Dockerfile.native 
                    -t quarkus/getting-started .
docker run -i --rm -p 8080:8080 quarkus/getting-started
----

// tag::update_11_6[]
You can use `quarkus.native.container-runtime` to select the container runtime to use.
Now `docker` (default) and `podman` are the valid options.

[source, bash]
----
./mvnw package -Pnative -Dquarkus.native.container-runtime=podman
----
// end::update_11_6[]

// tag::update_1_6[]
To configure native application, you can create a `config` directory at the same place as the native file and place an `application.properties` file inside. `config/application.properties`.
// end::update_1_6[]

== Container Images Creation

// tag::update_14_22[]
You can levarage to Quarkus to generation and release of Docker containers.
It provides several extensions to make it so.

[source, shell-session]
----
mvn clean package 
            -Dquarkus.container-image.build=true 
            -Dquarkus.container-image.push=true 
            -Dquarkus.container-image.registry=quay.io
----

Prefix is `quarkus.container-image`:

`group`::
The group/repository of the image. (default: the `${user.name}`)

`name`::
The name of the image. (default: the application name)

`tag`::
The tag of the image. (default: the application version)

`registry`::
The registry to use for pushing. (default: `docker.io`)

`username`::
The registry username.

`password`::
The registry password.

`insecure`::
Flag to allow insecure registries. (default: `false`)

`build`::
Boolean to set if image should be built. (default: `false`)

`push`::
Boolean to set if image should be pushed. (default: `false`)

*JIB*

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-container-image-jib"
----

Prefix is `quarkus.container-image-jib`:

`base-jvm-image`::
The base image to use for the jib build. (default: `fabric8/java-alpine-openjdk8-jre`)

`base-native-image`::
The base image to use for the native build. (default: `registry.access.redhat.com/ubi8/ubi-minimal`)

`jvm-arguments`::
The arguments to pass to java. (default: `-Dquarkus.http.host=0.0.0.0,-Djava.util.logging.manager=org.jboss.logmanager.LogManager`)

`native-arguments`::
The arguments to pass to the native application. (default: `-Dquarkus.http.host=0.0.0.0`)

`environment-variables`::
Map of environment variables.

*Docker* 

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-container-image-docker"
----

Prefix is `quarkus.container-image-s2i`:

`dockerfile-jvm-path`::
Path to the JVM Dockerfile. (default: `${project.root}/src/main/docker/Dockerfile.jvm`)

`dockerfile-native-path`::
Path to the native Dockerfile. (default: `${project.root}/src/main/docker/Dockerfile.native`)

*S2I*

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-container-image-s2i"
----

Prefix is `quarkus.container-image-docker`:

`base-jvm-image`::
The base image to use for the s2i build. (default: `fabric8/java-alpine-openjdk8-jre`)

`base-native-image`::
The base image to use for the native build. (default: `registry.access.redhat.com/ubi8/ubi-minimal`)
// end::update_14_22[]

== Kubernetes

Quarks can use https://github.com/dekorateio/dekorate[Dekorate] to generate Kubernetes resources.

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-kubernetes"
----

Running `./mvnw package` the Kubernetes resources are created at `target/kubernetes/` directory.

`quarkus.kubernetes.group`::
Set Docker Username. (default: Current username OS)

`quarkus.application.name`::
Project name. (default: Current project name)

Generated resource is integrated with <<Observability, MicroProfile Health annotations>>.

// tag::update_11_3[]
Also, you can customize the generated resource by setting the new values in `application.properties`:

[source, properties]
----
quarkus.kubernetes.replicas=3

quarkus.kubernetes.labelsfoo=bar

quarkus.kubernetes.readiness-probe.period-seconds=45

quarkus.kubernetes.mounts.github-token.path=/deployment/github
quarkus.kubernetes.mounts.github-token.read-only=true
quarkus.kubernetes.secret-volumes.github-token.volume-name=github-token
quarkus.kubernetes.secret-volumes.github-token.secret-name=greeting-security
quarkus.kubernetes.secret-volumes.github-token.default-mode=420

quarkus.docker.registry=quay.io
----

All possible values are explained at https://quarkus.io/guides/kubernetes#configuration-options.
// end::update_11_3[]

*Kubernetes Deployment Targets*
// tag::update_12_4[]

You can generate different resources setting the property `quarkus.kubernetes.deployment.target`.

Possible values are `kubernetes`, `openshift` and `knative`.
The default value is `kubernetes`.
// end::update_12_4[]

// tag::update_14_23[]
List of configuration options:

kubernetes:: https://quarkus.io/guides/kubernetes#configuration-options
openshift:: https://quarkus.io/guides/kubernetes#openshift
Knative:: https://quarkus.io/guides/kubernetes#knative
// end::update_14_23[]

*Deployment*

// tag::update_14_24[]
To deploy automatically the generated resources, you need to set `quarkus.container.deploy` flag to `true`.

[source, shell-session]
----
mvn clean package -Dquarkus.kubernetes.deploy=true
----

To deploy the application, the extension uses the `https://github.com/fabric8io/kubernetes-client[Fabric8 Kubernetes Client, window="_blank"].
All options described at <<Kubernetes Client>> are valid here.

TIP: <<Container Images Creation>> integrates with Kubernetes extension, so no need of extra properties.

// end::update_14_24[]

== Kubernetes Client
// tag::update_4_5[]
Quarkus integrates with https://github.com/fabric8io/kubernetes-client[Fabric8 Kubernetes Client, window="_blank"].

[source, terminal]
----
./mvnw quarkus:add-extension 
    -Dextensions="quarkus-kubernetes-client"
----

// tag::update_6_5[]
List of Kubernetes client parameters.

`quarkus.kubernetes-client` as prefix is skipped in the next table.

`trust-certs`::
Trust self-signed certificates. (default: `false`)

`master-url`::
URL of Kubernetes API server.

`namesapce`::
Default namespace.

`ca-cert-file`::
CA certificate data.

`client-cert-file`::
Client certificate file.

`client-cert-data`::
Client certificate data.

`client-key-data`::
Client key data.

`client-key-algorithm`::
Client key algorithm.

`client-key-passphrase`::
Client key passphrase.

`username`::
Username.

`password`::
Password.

`watch-reconnect-interval`::
Watch reconnect interval. (default: `PT1S`)

`watch-reconnect-limit`::
Maximum reconnect attempts. (default: `-1`)

`connection-timeout`::
Maximum amount of time to wait for a connection. (default: `PT10S`)

`request-timeout`::
Maximum amount of time to wait for a request. (default: `PT10S`)

`rolling-timeout`::
Maximum amount of time to wait for a rollout. (default: ``PT15M``)

`http-proxy`::
HTTP proxy used to access the Kubernetes.

`https-proxy`::
HTTPS proxy used to access the Kubernetes.

`proxy-username`::
Proxy username.

`proxy-password`::
Proxy password.

`no-proxy`::
IP addresses or hosts to exclude from proxying
// end::update_6_5[]

Or programmatically:

[source, java]
----
@Dependent
public class KubernetesClientProducer {

    @Produces
    public KubernetesClient kubernetesClient() {
        Config config = new ConfigBuilder()
            .withMasterUrl("https://mymaster.com")
            .build();
        return new DefaultKubernetesClient(config);
    }
}
----

And inject it on code:

[source, java]
----
@Inject
KubernetesClient client;

ServiceList myServices = client.services().list();

Service myservice = client.services()
        .inNamespace("default")
        .withName("myservice")
        .get();

CustomResourceDefinitionList crds = client
        .customResourceDefinitions()
        .list();

dummyCRD = new CustomResourceDefinitionBuilder()
        ...
        .build()
client.customResourceDefinitions()
        .create(dummyCRD);
----
// end::update_4_5[]

*Testing*

// tag::update_5_9[]
Quarkus provides a Kubernetes Mock test resource that starts a mock of Kubernetes API server and sets the proper environment variables needed by Kubernetes Client.

Register next dependency: `io.quarkus:quarkus-test-kubernetes-client:test`.

[source, java]
----
@QuarkusTestResource(KubernetesMockServerTestResource.class)
@QuarkusTest
public class KubernetesClientTest {
    
    @MockServer
    private KubernetesMockServer mockServer;

    @Test
    public void test() {
        final Pod pod1 = ...
        mockServer
            .expect()
            .get()
            .withPath("/api/v1/namespaces/test/pods")
            .andReturn(200,
                new PodListBuilder()
                .withNewMetadata()
                .withResourceVersion("1")
                .endMetadata()
                .withItems(pod1, pod2)
                .build())
            .always();
    }
}
----
// end::update_5_9[]

== Amazon Lambda
// tag::update_1_10[]
Quarkus integrates with Amazon Lambda.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-amazon-lambda"
----

And then implement `com.amazonaws.services.lambda.runtime.RequestHandler` interface.

[source, java]
----
public class TestLambda 
        implements RequestHandler<MyInput, MyOutput> {
    @Override
    public MyInput handleRequest(MyOutput input, 
                                    Context context) {
    }
}
----

// tag::update_9_4[]
You can set the handler name by using `quarkus.lambda.handler` property or by annotating the Lambda with the CDI `@Named` annotation.
// end::update_9_4[]

*Test*

You can write tests for Amazon lambdas:

[source, xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-test-amazon-lambda</artifactId>
  <scope>test</scope>
</dependency>
----

[source, java]
----
@Test
public void testLambda() {
    MyInput in = new MyInput();
    in.setGreeting("Hello");
    in.setName("Stu");
    MyOutput out = LambdaClient.invoke(MyOutput.class, in);
}
----
// end::update_1_10[]

// tag::update_11_8[]
To scaffold a AWS Lambda run:

[source, bash]
----
mvn archetype:generate \
    -DarchetypeGroupId=io.quarkus \
    -DarchetypeArtifactId=quarkus-amazon-lambda-archetype \
    -DarchetypeVersion={version}
----
// end::update_11_8[]

== Azure Functions

// tag::update_8_6[]
Quarkus can make a microservice be deployable to the Azure Functions.

To scaffold a deployable microservice to the Azure Functions run:

[source, bash]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.quarkus \
  -DarchetypeArtifactId=quarkus-azure-functions-http-archetype \
  -DarchetypeVersion={version}
----
// end::update_8_6[]