== Native Executable

You can build a native image by using GraalVM.
The common use case is creating a Docker image so you can execute the next commands:

[source, bash]
----
./mvnw package -Pnative -Dquarkus.native.container-build=true

docker build -f src/main/docker/Dockerfile.native 
                    -t quarkus/getting-started .
docker run -i --rm -p 8080:8080 quarkus/getting-started
----

// tag::update_11_6[]
You can use `quarkus.native.container-runtime` to select the container runtime to use.
Now `docker` (default) and `podman` are the valid options.

[source, bash]
----
./mvnw package -Pnative -Dquarkus.native.container-runtime=podman
----
// end::update_11_6[]

// tag::update_1_6[]
To configure native application, you can create a `config` directory at the same place as the native file and place an `application.properties` file inside. `config/application.properties`.
// end::update_1_6[]

*SSL*

// tag::update_14_28[]
To create a native image with SSL you need to copy SunEC library and certificates:

Java 8:

[source, Dockerfile]
----
FROM quay.io/quarkus/ubi-quarkus-native-image:{graalvm-version}-java8 as nativebuilder
RUN mkdir -p /tmp/ssl-libs/lib \
  && cp /opt/graalvm/jre/lib/security/cacerts /tmp/ssl-libs \
  && cp /opt/graalvm/jre/lib/amd64/libsunec.so /tmp/ssl-libs/lib/

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=nativebuilder /tmp/ssl-libs/ /work/
COPY target/*-runner /work/application
RUN chmod 775 /work /work/application
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djava.library.path=/work/lib", "-Djavax.net.ssl.trustStore=/work/cacerts"]
----

Java 11:

[source, Dockerfile]
----
FROM quay.io/quarkus/ubi-quarkus-native-image:{graalvm-version}-java11 as nativebuilder
RUN mkdir -p /tmp/ssl-libs/lib \
  && cp /opt/graalvm/lib/security/cacerts /tmp/ssl-libs \
  && cp /opt/graalvm/lib/libsunec.so /tmp/ssl-libs/lib/

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=nativebuilder /tmp/ssl-libs/ /work/
COPY target/*-runner /work/application
RUN chmod 775 /work /work/application
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0", "-Djava.library.path=/work/lib", "-Djavax.net.ssl.trustStore=/work/cacerts"]
----
// end::update_14_28[]

*Inclusion of resources*
// tag::update_16_2[]

By default, no resources are included in native executable.
`quarkus.native.resources.includes` allows to set glob expressions to include resources based on  `src/main/resources` path.

Given `src/main/resources/foo/selected.png`:

[source, properties]
----
quarkus.native.resources.includes=foo/**
----
// end::update_16_2[]

== Container Images Creation

// tag::update_14_22[]
You can levarage to Quarkus to generation and release of Docker containers.
It provides several extensions to make it so.

[source, shell-session]
----
mvn clean package 
            -Dquarkus.container-image.build=true 
            -Dquarkus.container-image.push=true 
            -Dquarkus.container-image.registry=quay.io
----

Prefix is `quarkus.container-image`:

`group`::
The group/repository of the image. (default: the `${user.name}`)

`name`::
The name of the image. (default: the application name)

`tag`::
The tag of the image. (default: the application version)

// tag::update_16_6[]
`additional-tags`:: 
Additional tags of the container image.
// end::update_16_6[]

`registry`::
The registry to use for pushing. (default: `docker.io`)

`username`::
The registry username.

`password`::
The registry password.

`insecure`::
Flag to allow insecure registries. (default: `false`)

`build`::
Boolean to set if image should be built. (default: `false`)

`push`::
Boolean to set if image should be pushed. (default: `false`)

*Jib*

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-container-image-jib"
----

Prefix is `quarkus.container-image-jib`:

`base-jvm-image`::
The base image to use for the jib build. (default: `fabric8/java-alpine-openjdk8-jre`)

`base-native-image`::
The base image to use for the native build. (default: `registry.access.redhat.com/ubi8/ubi-minimal`)

`jvm-arguments`::
The arguments to pass to java. (default: `-Dquarkus.http.host=0.0.0.0,-Djava.util.logging.manager=org.jboss.logmanager.LogManager`)

`native-arguments`::
The arguments to pass to the native application. (default: `-Dquarkus.http.host=0.0.0.0`)

`environment-variables`::
Map of environment variables.

*Docker* 

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-container-image-docker"
----

Prefix is `quarkus.container-image-s2i`:

`dockerfile-jvm-path`::
Path to the JVM Dockerfile. (default: `${project.root}/src/main/docker/Dockerfile.jvm`)

`dockerfile-native-path`::
Path to the native Dockerfile. (default: `${project.root}/src/main/docker/Dockerfile.native`)

*S2I*

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-container-image-s2i"
----

Prefix is `quarkus.container-image-docker`:

`base-jvm-image`::
The base image to use for the s2i build. (default: `fabric8/java-alpine-openjdk8-jre`)

`base-native-image`::
The base image to use for the native build. (default: `registry.access.redhat.com/ubi8/ubi-minimal`)
// end::update_14_22[]

== Kubernetes

Quarks can use https://github.com/dekorateio/dekorate[Dekorate] to generate Kubernetes resources.

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-kubernetes"
----

Running `./mvnw package` the Kubernetes resources are created at `target/kubernetes/` directory.

TIP: <<Container Images Creation>> integrates with Kubernetes extension, so no need of extra Kubernetes properties.

Generated resource is integrated with <<Observability, MicroProfile Health annotations>>.

// tag::update_11_3[]
Also, you can customize the generated resource by setting the new values in `application.properties`:

[source, properties]
----
quarkus.kubernetes.replicas=3

quarkus.kubernetes.labelsfoo=bar

quarkus.kubernetes.readiness-probe.period-seconds=45

quarkus.kubernetes.mounts.github-token.path=/deployment/github
quarkus.kubernetes.mounts.github-token.read-only=true

quarkus.kubernetes.secret-volumes.github-token.volume-name=github-token
quarkus.kubernetes.secret-volumes.github-token.secret-name=greeting-security
quarkus.kubernetes.secret-volumes.github-token.default-mode=420

quarkus.kubernetes.config-map-volumes.github-token.config-map-name=my-secret

quarkus.kubernetes.expose=true

quarkus.kubernetes.env.vars.my-env-var=foobar
quarkus.kubernetes.env.configmaps=my-config-map,another-config-map
quarkus.kubernetes.env.secrets=my-secret,my-other-secret
----

All possible values are explained at https://quarkus.io/guides/kubernetes#configuration-options.
// end::update_11_3[]

*Labels and Annotations*

// tag::update_14_38[]
The generated manifest use the Kubernetes recommended labels and annotations.

[source, json]
----
"labels" : {
    "app.kubernetes.io/part-of" : "todo-app",
    "app.kubernetes.io/name" : "todo-rest",
    "app.kubernetes.io/version" : "1.0-rc.1"
}

"annotations": {
    "app.quarkus.io/vcs-url" : "<some url>",
    "app.quarkus.io/commit-id" : "<some git SHA>",
}
----

You can override the labels by using the next properties:

[source, properties]
----
quarkus.kubernetes.part-of=todo-app
quarkus.kubernetes.name=todo-rest
quarkus.kubernetes.version=1.0-rc.1
----

Or add new labels and/or annotations:

[source, properties]
----
quarkus.kubernetes.labels.foo=bar
quarkus.kubernetes.annotations.foo=bar
----
// end::update_14_38[]

*Kubernetes Deployment Targets*
// tag::update_12_4[]

You can generate different resources setting the property `quarkus.kubernetes.deployment-target`.

Possible values are `kubernetes`, `openshift` and `knative`.
The default value is `kubernetes`.
// end::update_12_4[]

// tag::update_14_23[]
List of configuration options:

kubernetes:: https://quarkus.io/guides/kubernetes#configuration-options
openshift:: https://quarkus.io/guides/kubernetes#openshift
Knative:: https://quarkus.io/guides/kubernetes#knative
// end::update_14_23[]

*Using Existing Resources* 

// tag::update_16_16[]
You an provide your Kubernetes resources in form of yaml/json and they will provide additional resources or be used as base for the generation process:

Resources are added in `src/main/kubernetes` directory with the target name (`kubernetes.json`, `openshift.json`, `knative.json`, or the yml equivalents) with one orm ore Kubernetes resources.
Any resource found will be added in the generated manifests.
If one of the provided resources has the same name as one of the generated ones, then the generated resource will be created on top of the provided resource, respecting existing content.

To override the name of the generated resource you can use: `quarkus.kubernetes.name`, `quarkus.openshift.name` and `quarkus.knative.name`.
// end::update_16_16[]

*Deployment*

// tag::update_14_24[]
To deploy automatically the generated resources, you need to set `quarkus.container.deploy` flag to `true`.

[source, shell-session]
----
mvn clean package -Dquarkus.kubernetes.deploy=true
----

TIP: If you set this flag to `true`, the `build` and `push` flags from container-image are set to `true` too. 

To deploy the application, the extension uses the https://github.com/fabric8io/kubernetes-client.
All options described at <<Kubernetes Client>> are valid here.
// end::update_14_24[]

== Minikube

// tag::update_16_22[]
Quarkus has a Minikube extension which creates Kubernetes manifests that are tailored for Minikube.

[source, shell-session]
----
./mvnw quarkus:add-extension 
    -Dextensions="minikube"
----

TIP: Remember to execute `eval $(minikube -p minikube docker-env)` to build images directly inside Minkube cluster.
// end::update_16_22[]

== OpenShift

// tag::update_14_29[]
Instead of adding Kubernetes extension, set container image s2i and the `target` to `openshift` for working with OpenShift, an extension grouping all of the is created:

[source, shell-session]
----
./mvnw quarkus:add-extension 
    -Dextensions="openshift"
----
// end::update_14_29[]

<<<

== Kubernetes Configuration Extension

// tag::update_15_14[]

Integration between MicroProfile Config spec and ConfigMaps:

[source, bash]
----
./mvnw quarkus:add-extensions 
    -Dextensions="quarkus-kubernetes-config"
----

[source, properties]
----
quarkus.kubernetes-config.enabled=true
quarkus.kubernetes-config.config-maps=cmap1,cmap2
----

[source, java]
----
@ConfigProperty(name = "some.prop1")
String someProp1;

@ConfigProperty(name = "some.prop2")
String someProp2;
----

If the config key is a Quarkus configuration file `application.properties`/`application.yaml`, the content is parsed and each key of the configuration file is used as config property.

List of Kubernetes Config parameters.

`quarkus.kubernetes-config` as prefix is skipped in the next table.

`enabled`::
The application will attempt to look up the configuration from the API server. (default: `false`)

`fail-on-missing-config`::
The application will not start if any of the configured config sources cannot be located. (default: `true`)

`config-maps`::
ConfigMaps to look for in the namespace that the Kubernetes Client has been configured for. Supports CSV.

`secrets`::
Secrets to look for in the namespace that the Kubernetes Client has been configured for. Supports CSV.
// end::update_15_14[]

== Kubernetes Client
// tag::update_4_5[]
Quarkus integrates with https://github.com/fabric8io/kubernetes-client[Fabric8 Kubernetes Client, window="_blank"].

[source, terminal]
----
./mvnw quarkus:add-extension 
    -Dextensions="quarkus-kubernetes-client"
----

// tag::update_6_5[]
List of Kubernetes client parameters.

`quarkus.kubernetes-client` as prefix is skipped in the next table.

`trust-certs`::
Trust self-signed certificates. (default: `false`)

<<<

`master-url`::
URL of Kubernetes API server.

`namesapce`::
Default namespace.

`ca-cert-file`::
CA certificate data.

`client-cert-file`::
Client certificate file.

`client-cert-data`::
Client certificate data.

`client-key-data`::
Client key data.

`client-key-algorithm`::
Client key algorithm.

`client-key-passphrase`::
Client key passphrase.

`username`::
Username.

`password`::
Password.

`watch-reconnect-interval`::
Watch reconnect interval. (default: `PT1S`)

`watch-reconnect-limit`::
Maximum reconnect attempts. (default: `-1`)

`connection-timeout`::
Maximum amount of time to wait for a connection. (default: `PT10S`)

`request-timeout`::
Maximum amount of time to wait for a request. (default: `PT10S`)

`rolling-timeout`::
Maximum amount of time to wait for a rollout. (default: ``PT15M``)

`http-proxy`::
HTTP proxy used to access the Kubernetes.

`https-proxy`::
HTTPS proxy used to access the Kubernetes.

`proxy-username`::
Proxy username.

`proxy-password`::
Proxy password.

`no-proxy`::
IP addresses or hosts to exclude from proxying
// end::update_6_5[]

Or programmatically:

[source, java]
----
@Dependent
public class KubernetesClientProducer {

    @Produces
    public KubernetesClient kubernetesClient() {
        Config config = new ConfigBuilder()
            .withMasterUrl("https://mymaster.com")
            .build();
        return new DefaultKubernetesClient(config);
    }
}
----

And inject it on code:

[source, java]
----
@Inject
KubernetesClient client;

ServiceList myServices = client.services().list();

Service myservice = client.services()
        .inNamespace("default")
        .withName("myservice")
        .get();

CustomResourceDefinitionList crds = client
        .customResourceDefinitions()
        .list();

dummyCRD = new CustomResourceDefinitionBuilder()
        ...
        .build()
client.customResourceDefinitions()
        .create(dummyCRD);
----
// end::update_4_5[]

*Testing*

// tag::update_5_9[]
Quarkus provides a Kubernetes Mock test resource that starts a mock of Kubernetes API server and sets the proper environment variables needed by Kubernetes Client.

Register next dependency: `io.quarkus:quarkus-test-kubernetes-client:test`.

[source, java]
----
@QuarkusTestResource(KubernetesMockServerTestResource.class)
@QuarkusTest
public class KubernetesClientTest {
    
    @MockServer
    private KubernetesMockServer mockServer;

    @Test
    public void test() {
        final Pod pod1 = ...
        mockServer
            .expect()
            .get()
            .withPath("/api/v1/namespaces/test/pods")
            .andReturn(200,
                new PodListBuilder()
                .withNewMetadata()
                .withResourceVersion("1")
                .endMetadata()
                .withItems(pod1, pod2)
                .build())
            .always();
    }
}
----
// end::update_5_9[]

== AWS Lambda
// tag::update_1_10[]
Quarkus integrates with Amazon Lambda.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-amazon-lambda"
----

And then implement `com.amazonaws.services.lambda.runtime.RequestHandler` interface.

[source, java]
----
public class TestLambda 
        implements RequestHandler<MyInput, MyOutput> {
    @Override
    public MyInput handleRequest(MyOutput input, 
                                    Context context) {
    }
}
----

// tag::update_15_2[]
The interface `com.amazonaws.services.lambda.runtime.RequestStreamHandler` is also supported.
// end::update_15_2[]

// tag::update_15_3[]
The interface `com.amazon.ask.SkillStreamHandler` is also supported.
// end::update_15_3[]

// tag::update_9_4[]
You can set the handler name by using `quarkus.lambda.handler` property or by annotating the Lambda with the CDI `@Named` annotation.
// end::update_9_4[]

*Test*

You can write tests for Amazon lambdas:

[source, xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-test-amazon-lambda</artifactId>
  <scope>test</scope>
</dependency>
----

[source, java]
----
@Test
public void testLambda() {
    MyInput in = new MyInput();
    in.setGreeting("Hello");
    in.setName("Stu");
    MyOutput out = LambdaClient.invoke(MyOutput.class, in);
}
----
// end::update_1_10[]

// tag::update_11_8[]
To scaffold a AWS Lambda run:

[source, bash]
----
mvn archetype:generate \
    -DarchetypeGroupId=io.quarkus \
    -DarchetypeArtifactId=quarkus-amazon-lambda-archetype \
    -DarchetypeVersion={version}
----
// end::update_11_8[]

== Azure Functions

// tag::update_8_6[]
Quarkus can make a microservice be deployable to the Azure Functions.

To scaffold a deployable microservice to the Azure Functions run:

[source, bash]
----
mvn archetype:generate \
  -DarchetypeGroupId=io.quarkus \
  -DarchetypeArtifactId=quarkus-azure-functions-http-archetype \
  -DarchetypeVersion={version}
----
// end::update_8_6[]

== Funqy

// tag::update_16_27[]
Quarkus Funqy is part of Quarkus’s serverless strategy and aims to provide a portable Java API to write functions deployable to various FaaS environments like AWS Lambda, Azure Functions, Knative, and Knative events.

[source, java]
----
public class GreetingFunction {

    @Inject
    GreetingService service;

    @io.quarkus.funqy.Funq
    public String greet(String name) {}

    @io.quarkus.funqy.Funq("HelloCustomer")
    public String greet(Customer name) {}

    @Funq
    public Greeting greet(Friend friend, 
        @io.quarkus.funqy.Context AwsContext ctx) {}
}
----

In case of Amazon Lambda, only one Funqy function can be exported per Amazon Lambda deployment.
If there is only one method annotated with `@Funq` then no prob, if not, you need to set the function name with `quarkus.funqy.export` property.

// end::update_16_27[]

== Funqy HTTP

// tag::update_16_28[]
You can invoke on Funqy functions in a pure HTTP environment with simple adding the Funqy HTTP extension.

[source, xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-funqy-http</artifactId>
</dependency>
----
// end::update_16_28[]

== Funqy Cloud Events

// tag::update_16_29[]

Add the extension:

[source, xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-funqy-knative-events</artifactId>
</dependency>
----

[source, java]
----
@Funq
public String defaultChain(String input) {}
----

The Cloud Event type that triggers the function is `defaultChain`. 
It generates a response that triggers a new Cloud Event whose type is `defaultChain.output` and the event source is `defaultChain`.

It can be changed by using the next properties:

[source, properties]
----
quarkus.funqy.knative-events.mapping.defaultChain.trigger=configChain.output
quarkus.funqy.knative-events.mapping.defaultChain.response-type=annotated
quarkus.funqy.knative-events.mapping.defaultChain.response-source=configChain
----

The properties are of form: `quarkus.funqy.knative-events.mapping.{function name}.`.

Also can be overriden with `@io.quarkus.funqy.knative.events.CloudEventMapping` annotation.

[source, java]
----
@Funq
@CloudEventMapping(trigger = "annotated", responseSource = "annotated", responseType = "lastChainLink")
public String annotatedChain(String input) {}
----

`responseType` chains `annotatedChain` response to `lastChainLink` function.

[source, java]
----
@Funq
public void lastChainLink(String input, 
            @Context io.quarkus.funqy.knative.events.CloudEvent event) {}
----

A K-Native Trigger looks like:

[source, yaml]
----
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: defaultchain
spec:
  filter:
    attributes:
      type: defaultChain
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: funqy-knative-events-quickstart
----

And to `curl` from inside the Kubernetes cluster:

[source, bash-shell]
----
curl -v "http://default-broker.knativetutorial.svc.cluster.local" \
-X POST \
-H "Ce-Id: 1234" \
-H "Ce-Specversion: 1.0" \
-H "Ce-Type: defaultChain" \
-H "Ce-Source: curl" \
-H "Content-Type: application/json" \
-d '"Start"'
----
// end::update_16_29[]