== Apache Camel
// tag::update_2_1[]
Apache Camel Quarkus has its own site: https://github.com/apache/camel-quarkus
// end::update_2_1[]

== WebSockets
// tag::update_2_2[]
Quarkus can be used to handling web sockets.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-websockets"
----

And web sockets classes can be used:

[source, java]
----
@ServerEndpoint("/chat/{username}")
@ApplicationScoped
public class ChatSocket {

    @OnOpen
    public void onOpen(Session session, 
                @PathParam("username") String username) {}

    @OnClose
    public void onClose(..) {}

    @OnError
    public void onError(..., Throwable throwable) {}

    @OnMessage
    public void onMessage(...) {}

}
----
// end::update_2_2[]

== OpenAPI
// tag::update_2_3[]
Quarkus can expose its API description as https://swagger.io/specification/[OpenAPI, window="_blank"] spec and test it using https://swagger.io/tools/swagger-ui/[Swagger UI, window="_blank"].

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-smallrye-openapi"
----

Then you only need to access to `/openapi` to get OpenAPI v3 spec of services.

// tag::update_3_5[]
You can update the OpenApi path by setting `quarkus.smallrye-openapi.path` property.
// end::update_3_5[]

Also, in case of starting Quarkus application in `dev` or `test` mode, Swagger UI is accessible at `/swagger-ui`.
If you want to use it in production mode you need to set `quarkus.swagger-ui.always-include` property to `true`.

You can update the Swagger UI path by setting `quarkus.swagger-ui.path` property.

[source, properties]
----
quarkus.swagger-ui.path=/my-custom-path
----
// end::update_2_3[]

// tag::update_21_7[]
Possible Swagger UI options with `quarkus.swagger-ui` prefix:

`urls`::
The urls that will be included as options. (ie `quarkus.swagger-ui.urls.petstore=https://petstore.swagger.io/v2/swagger.json`)

`urls-primary-name`::
If urls option is used, this will be the name of the default selection.

`title`::
The html title for the page.

`theme`::
Swagger UI theme to be used.

`footer`::
A footer for the html page. Nothing by default.

`deep-linking`::
Enables deep linking for tags and operations.

`display-operation-id`::
Controls the display of operationId in operations list.

`default-models-expand-depth`::
The default expansion depth for models.

`default-model-expand-depth`::
The default expansion depth for the model on the model-example section.

`default-model-rendering`::
Controls how the model is shown when the API is first rendered.

`display-request-duration`::
Controls the display of the request duration (in milliseconds) for "Try it out" requests.

`doc-expansion`::
Controls the default expansion setting for the operations and tags.

`filter`::
Enables filtering.

`max-displayed-tags`::
Limits the number of tagged operations displayed to at most this many.

`operations-sorter`::
Apply a sort to the operation list of each API. (`alpha`, `method`, `function`)

`show-extensions`::
Controls the display of vendor extension.

`show-common-extensions`::
Controls the display of extensions.

`tag-sorter`::
Apply a sort to the tag list of each API.

`on-complete`::
Provides a mechanism to be notified when Swagger UI has finished rendering a newly provided definition.

`syntax-highlight`::
Set to false to deactivate syntax highlighting of payloads and cURL command.

`oauth2-redirect-url`::
OAuth redirect URL.

`request-interceptor`::
Function to intercept remote definition, "Try it out", and OAuth 2.0 requests.

`request-curl-options`::
Array of command line options available to the curl command.

`response-interceptor`::
 Function to intercept remote definition, "Try it out", and OAuth 2.0 responses.

`show-mutated-request`::
Uses the mutated request returned from a requestInterceptor to produce the curl command in the UI.

`supported-submit-methods`::
List of HTTP methods that have the "Try it out" feature enabled.

`validator-url`::
Swagger UI attempts to validate specs against swagger.io's online validator.

`with-credentials`::
Enables passing credentials, as defined in the Fetch standard, in CORS requests that are sent by the browser.

`model-property-macro`::
Function to set default values to each property in model.

`parameter-macro`::
Function to set default value to parameters.

`persist-authorization`::
It persists authorization data and it would not be lost on browser close/refresh.

`layout`::
The name of a component available via the plugin system to use as the top-level layout for Swagger UI.

`plugins`::
A list of plugin functions to use in Swagger UI.

`presets`::
A list of presets to use in Swagger UI.
// end::update_21_7[]

// tag::update_6_6[]
You can customize the output by using Open API v3 annotations.

[source, java]
----
@Schema(name="Developers", 
        description="POJO that represents a developer.")
public class Developer {
    @Schema(required = true, example = "Alex")
    private String name;
}

@POST
@Path("/developer")
@Operation(summary = "Create deeloper",
           description = "Only be done by admin.")
public Response createDeveloper(
        @RequestBody(description = "Developer object", 
            required = true,
            content = @Content(schema = 
            @Schema(implementation = Developer.class))) 
                Developer developer)
----

All possible annotations can be seen at https://github.com/eclipse/microprofile-open-api/tree/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations[org.eclipse.microprofile.openapi.annotations, window="_blank"] package.
// end::update_6_6[]

// tag::update_8_10[]
You can also serve OpenAPI Schema from static files instead of dynamically generated from annotation scanning.

You need to put OpenAPIdocumentation under `META-INF` directory (ie: `META-INF/openapi.yaml`).

A request to `/openapi` will serve the combined OpenAPI document from the static file and the generated from annotations.
You can disable the scanning documents by adding the next configuration property: `mp.openapi.scan.disable=true`.

Other valid document paths are: `META-INF/openapi.yml`, `META-INF/openapi.json`, `WEB-INF/classes/META-INF/openapi.yml`, `WEB-INF/classes/META-INF/openapi.yaml`, `WEB-INF/classes/META-INF/openapi.json`.
// end::update_8_10[]

// tag::update_19_4[]
You can store generated OpenAPI schema if `quarkus.swagger-ui.store-schema-directory` is set.
// end::update_19_4[]

// tag::update_24_4[]
Possible OpenAPI options with `quarkus.smallrye-openapi` prefix:

path::
The path at which to register the OpenAPI Servlet. (default: `openapi`)

store-schema-directory::
The generated OpenAPI schema documents will be stored here on build.

security-scheme::
Add a certain SecurityScheme with config. (`basic`, `jwt`, `oidc`, `oauth2Implicit`)

security-scheme-name::
Add a Security Scheme name to the generated OpenAPI document. (default: `SecurityScheme`)

security-scheme-description::
Add a description to the Security Scheme. (default: `Authentication`)

basic-security-scheme-value::
Add a scheme value to the Basic HTTP Security Scheme. (default: `basic`)

jwt-security-scheme-value::
Add a scheme value to the JWT Security Scheme. (default: `bearer`)

jwt-bearer-format::
Add a bearer format to the JWT Security Scheme. (default: `JWT`)

oidc-open-id-connect-url::
Add a openIdConnectUrl value to the OIDC Security Scheme

oauth2-implicit-refresh-url::
Add a implicit flow refreshUrl value to the OAuth2 Security Scheme

oauth2-implicit-authorization-url::
Add an implicit flow authorizationUrl value to the OAuth2 Security Scheme

oauth2-implicit-token-url::
Add an implicit flow tokenUrl value to the OAuth2 Security Scheme
// end::update_24_4[]


== Mail Sender
// tag::update_2_5[]
You can send emails by using Quarkus Mailer extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-mailer"
----

You can inject two possible classes `io.quarkus.mailer.Mailer` for synchronous API or `io.quarkus.mailer.reactive.ReactiveMailer` for asynchronous/reactive API.

[source, java]
----
@Inject
Mailer mailer;
----

And then you can use them to send an email:

[source, java]
----
mailer.send(
    Mail.withText("to@acme.org", "Subject", "Body")
);
----

*Reactive Mail client*

// tag::update_14_14[]
[source, java]
----
@Inject
ReactiveMailer reactiveMailer;

CompletionStage<Response> stage = 
    reactiveMailer.send(
        Mail.withText("to@acme.org", "Subject", "Body")
    )
    .subscribeAsCompletionStage()
    .thenApply(x -> Response.accepted().build());
----

TIP: If you are using `quarkus-resteasy-mutiny`, you can return `io.smallrye.mutiny.Uni` type.

// end::update_14_14[]
`Mail` class contains methods to add `cc`, `bcc`, `headers`, `bounce address`, `reply to`, `attachments`, `inline attachments` and `html body`.

[source, java]
----
mailer.send(Mail.withHtml("to@acme.org", "Subject", body)
      .addInlineAttachment("quarkus.png",
            new File("quarkus.png"),
            "image/png", "<my-image@quarkus.io>"));
----

TIP: If you need deep control you can inject Vert.x mail client `@Inject  MailClient client;`

You need to configure SMTP properties to be able to send an email:

[source, properties]
----
quarkus.mailer.from=test@quarkus.io
quarkus.mailer.host=smtp.sendgrid.net
quarkus.mailer.port=465
quarkus.mailer.ssl=true
quarkus.mailer.username=....
quarkus.mailer.password=....
----

List of Mailer parameters.
`quarkus.` as a prefix is skipped in the next table.

|===	
|Parameter | Default | Description

a|`mailer.from`
|
a|Default address.

a|`mailer.mock`
a|false in `prod`, true in `dev` and `test`.
|Emails not sent, just printed and stored in a `MockMailbox`.

a|`mailer.bounce-address`
|
|Default address.

a|`mailer.host`
a|_mandatory_
|SMTP host.

a|`mailer.port`
|25
|SMTP port.

a|`mailer.username`
|
|The username.

a|`mailer.password`
|
|The password.

a|`mailer.ssl`
a|`false`
|Enables SSL.

a|`mailer.trust-all`
|false
|Trust all certificates.

a|`mailer.max-pool-size`
|10
|Max open connections .

a|`mailer.own-host-name`
|
a|Hostname for `HELO/EHLO` and `Message-ID`

a|`mailer.keep-alive`
a|`true`
|Connection pool enabled.

a|`mailer.disable-esmtp`
a|`false`
|Disable ESMTP.

a|`mailer.start-tls`
a|`OPTIONAL`
a|TLS security mode. `DISABLED`, `OPTIONAL`, `REQUIRED`.

a|`mailer.login`
a|`NONE`
a|Login mode. `NONE`, `OPTIONAL`, `REQUIRED`.

a|`mailer.auth-methods`
|All methods.
|Space-separated list.

a|`mailer.key-store`
|
|Path of the key store.

a|`mailer.key-store-password`
|
|Key store password.
|===
// tag::update_3_7[]
// tag::update_6_x[]
IMPORTANT: if you enable SSL for the mailer and you want to build a native executable, you will need to enable the SSL support `quarkus.ssl.native=true`. 
// end::update_6_x[]

*Testing*

If `quarkus.mailer.mock` is set to `true`, which is the default value in `dev` and `test` mode, you can inject `MockMailbox` to get the sent messages.

[source, java]
----
@Inject
MockMailbox mailbox;

@BeforeEach
void init() {
    mailbox.clear();
}

List<Mail> sent = mailbox
                    .getMessagesSentTo("to@acme.org");
----
// end::update_3_7[]

// end::update_2_5[]

== Scheduled Tasks
// tag::update_3_2[]
You can schedule periodic tasks with Quarkus.

[source, java]
----
@ApplicationScoped
public class CounterBean {

    @Scheduled(every="10s", delayed="1s")
    void increment() {}

    @Scheduled(cron="0 15 10 * * ?")
    void morningTask() {}
}
----

`every` and `cron` parameters can be surrounded with `{}` and the value is used as config property to get the value. 

[source java]
----
@Scheduled(cron = "{morning.check.cron.expr}")
void morningTask() {}
----

And configure the property into `application.properties`:

[source, properties]
----
morning.check.cron.expr=0 15 10 * * ?
----
// end::update_3_2[]

// tag::update_12_5[]
By default Quarkus expresion is used, but you can change that by setting `quarkus.scheduler.cron-type` property.

[source, properties]
----
quarkus.scheduler.cron-type=unix
----
// end::update_12_5[]

// tag::update_14_18[]
`org.quartz.Scheduler` can be injected as any other bean and scehdule jobs programmatically.

[source, java]
----
@Inject
org.quartz.Scheduler quartz;

quartz.scheduleJob(job, trigger);
----
// end::update_14_18[]


== Kogito
// tag::update_3_9[]
Quarkus integrates with http://www.kiegroup.org/[Kogito, window="_blank"], a next-generation business automation toolkit from Drools and jBPM projects for adding business automation capabilities.

To start using it you only need to add the next extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="kogito"
----
// end::update_3_9[]

== Apache Tika
// tag::update_5_8[]

Quarkus integrates with https://tika.apache.org/[Apache Tika, window="_blank"] to detect and extract metadata/text from different file types:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-tika"
----

[source, java]
----
@Inject
io.quarkus.tika.TikaParser parser;

@POST
@Path("/text")
@Consumes({ "text/plain", "application/pdf", 
            "application/vnd.oasis.opendocument.text" })
@Produces(MediaType.TEXT_PLAIN)
public String extractText(InputStream stream) {
    return parser.parse(stream).getText();
}
----

// tag::update_7_3[]
You can configure Apache Tika in `application.properties` file by using next properties prefixed with `quarkus`:

|===	
|Parameter | Default | Description

a|`tika.tika-config-path`
a|`tika-config.xml`
a|Path to the Tika configuration resource. 

a|`quarkus.tika.parsers`
a|
a|CSV of the abbreviated or full parser class to be loaded by the extension.

a|`tika.append-embedded-content`
a|`true`
a|The document may have other embedded documents. Set if autmatically append.
|===
// end::update_7_3[]
// end::update_5_8[]

== JGit
// tag::update_8_1[]

Quarkus integrates with https://www.eclipse.org/jgit/[JGit, window="_blank"] to integrate with Git repositories:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-jgit"
----

And then you can start using JGit:

[source, java]
----
try (Git git = Git.cloneRepository()
                  .setDirectory(tmpDir)
                  .setURI(url)
                  .call()) {
    return tmpDir.toString();
}
----

IMPORTANT: When running in native mode, make sure to configure SSL access correctly `quarkus.ssl.native=true` (https://quarkus.io/guides/native-and-ssl-guide[Native and SSL, window="_blank"]). 
// end::update_8_1[]

== Web Resources

// tag::update_8_9[]
You can serve web resources with Quarkus.
You need to place web resources at `src/main/resources/META-INF/resources` and then they are accessible (ie http://localhost:8080/index.html)
// end::update_8_9[]

// tag::update_9_6[]
By default static resources as served under the root context.
You can change this by using `quarkus.http.root-path` property.
// end::update_9_6[]

== Transactional Memory

// tag::update_10_6[]
Quarkus integrates with the Software Transactional Memory (STM) implementation provided by the https://narayana.io/docs/project/index.html[Narayana] project.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="narayana-stm"
----

Transactional objects must be interfaces and annotated with `org.jboss.stm.annotations.Transactional`.

[source, java]
----
@Transactional
@NestedTopLevel
public interface FlightService {
    int getNumberOfBookings();
    void makeBooking(String details);
}
----

The pessimistic strategy is the default one, you can change to optimistic by using `@Optimistic`.

Then you need to create the object inside `org.jboss.stm.Container`.

[source, java]
----
Container<FlightService> container = new Container<>(); 
FlightServiceImpl instance = new FlightServiceImpl(); 
FlightService flightServiceProxy = container.create(instance);
----

The implementation of the service sets the locking and what needs to be saved/restored:

[source, java]
----
import org.jboss.stm.annotations.ReadLock;
import org.jboss.stm.annotations.State;
import org.jboss.stm.annotations.WriteLock;

public class FlightServiceImpl 
    implements FlightService {
    @State
    private int numberOfBookings;

    @ReadLock
    public int getNumberOfBookings() {
        return numberOfBookings;
    }

    @WriteLock
    public void makeBooking(String details) {
        numberOfBookings += 1;
    }
}
----

Any member is saved/restored automatically (`@State` is not mandatory).
You can use `@NotState` to avoid behaviour.

*Transaction boundaries*

_Declarative_

 * `@NestedTopLevel`: Defines that the container will create a new top-level transaction for each method invocation.
 * `@Nested`: Defines that the container will create a new top-level or nested transaction for each method invocation.

_Programmatically_

[source, java]
----
AtomicAction aa = new AtomicAction(); 

aa.begin(); 
{
    try {
        flightService.makeBooking("BA123 ...");
        taxiService.makeBooking("East Coast Taxis ..."); 
        
        aa.commit();
    } catch (Exception e) {
        aa.abort(); 
    }
}
----
// end::update_10_6[]

== Quartz
// tag::update_12_2[]
Quarkus integrates with http://www.quartz-scheduler.org/[Quartz]  to schedule periodic clustered tasks.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quartz"
----

[source, java]
----
@ApplicationScoped
public class TaskBean {

    @Transactional
    @Scheduled(every = "10s")
    void schedule() {
        Task task = new Task();
        task.persist();
    }
}
----

To configure in clustered mode vida DataSource:

[source, application.properties]
----
quarkus.datasource.url=jdbc:postgresql://localhost/quarkus_test
quarkus.datasource.driver=org.postgresql.Driver
# ...

quarkus.quartz.clustered=true
quarkus.quartz.store-type=db
----

IMPORTANT: You need to define the datasource used by clustered mode and also import the database tables following the Quartz schema.
// end::update_12_2[]

// tag::update_19_5[]
Quartz can be configured usinf the following properties with `quarkus.quartz` prefix:

`clustered`::
Enable cluster mode or not.

`store-type`::
The type of store to use. Possible values: `ram`, `db` (default: `ram`)

`datasource`::
The name of the datasource to use.

`table-prefix`::
The prefix for quartz job store tables. (default: `QRTZ_`)

`trigger-listeners.<name>.class`::
Class name for the trigger.

`trigger-listeners.<name>.property-name`::
The properties passed to the class.

`job-listeners.<name>.class`::
Class name for the job.

`job-listeners.<name>.property-name`::
The properties passed to the class.

`plugins.<name>.class`::
Class name for the plugin.

`plugins.<name>.property-name`::
The properties passed to the class.

`instance-name`::
The name of the Quartz instance. (default: `QuarkusQuartzScheduler`)

`thread-count`::
The size of scheduler thread pool. (default: `25`)

`thread-priority`::
Thread priority of worker threads in the pool. (default: `5`)

`force-start`::
The scheduler will be started even if no scheduled business methods are found.

`start-mode`::
Scheduler can be started in different modes: `normal`, `forced` or `halted`. (default: `normal`)
// end::update_19_5[]

== Qute

// tag::update_12_8[]
Qute is a templating engine designed specifically to meet the Quarkus needs.
Templates should be placed by default at `src/main/resources/templates` aand subdirectories.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-resteasy-qute"
----

Templates can be defined in any format, in case of HTML:

[source, html]
.item.html
----
{@org.acme.Item item}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{item.name}</title>
</head>
<body>
    <h1>{item.name ?: 'Unknown'}</h1>
    <h2>{str:reverse('Hello')}</h2>
    <div>Price: {item.price}</div>
    {#if item.price > 100}
    <div>Discounted Price: {item.discountedPrice}</div>
    {/if}
</body>
</html>
----

First line is not mandatory but helps on doing property checks at compilation time.

// tag::update_19_2[]
Including templates passing parameters:

[source, html]
----
<html>
<head>
<meta charset="UTF-8">
<title>Simple Include</title>
</head>
<body>
  {#include foo limit=10 /}
</body>
</html>
----
// end::update_19_2[]

To render the template:

[source, java]
----
public class Item {
    public String name;
    public BigDecimal price;
}

@Inject
io.quarkus.qute.Template item;

@GET
@Path("{id}")
@Produces(MediaType.TEXT_HTML)
public TemplateInstance get(@PathParam("id") Integer id) {
    return item.data("item", service.findItem(id));
}

@TemplateExtension
static BigDecimal discountedPrice(Item item) {
    return item.price.multiply(new BigDecimal("0.9"));
}

@TemplateExtension(namespace = "str")
public static class StringExtensions {
  static String reverse(String val) {
      return new StringBuilder(val).reverse().toString();
  }
}
----

If `@ResourcePath` is not used in `Template` then the name of the field is used as file name.
In this case the file should be `src/main/resources/templates/item.{}`.
Extension of the file is not required to be set.

`discountedPrice` is not a field of the POJO but a method call.
Method definition must be annotated with `@TemplateExtension` and be static method.
First parameter is used to match the base object (`Item`).
// tag::update_13_8[]
`@TemplateExtension` can be used at class level:

[source, java]
----
@TemplateExtension
public class MyExtensions {
    static BigDecimal discountedPrice(Item item) {
        return item.price.multiply(new BigDecimal("0.9"));
    }
}
----

Methods with multiple parameters are supported too:

[source,html]
----
{item.discountedPrice(2)}
----

[source, java]
----
static BigDecimal discountedPrice(Item item, int scale) {
    return item.price.multiply(scale);
}
----
// end::update_13_8[]

// tag::update_14_4[]
Qute `for` syntax supports any instance of `Iterable`, `Map.EntrySet`, `Stream` or `Integer`.

[source, html]
----
{#for i in total}
  {i}:
{/for}
----
// end::update_14_4[]

// tag::update_14_27[]
The next map methods are supported:

[source, html]
----
{#for key in map.keySet}
{#for value in map.values}
{map.size}
{#if map.isEmpty}
{map['foo']
----

The next list methods are supported:

[source, html]
----
{list[0]}
----

The next number methods are supported:

[source, html]
----
{#if counter.mod(5) == 0}
----
// end::update_14_27[]

*Switch/When*

// tag::update_22_3[]
[source, html]
----
{#switch person.name}
  {#case 'John'}
    Hey John!
  {#case 'Mary'}
    Hey Mary!
{/switch}
----

[source, html]
----
{#when items.size}
  {#is 1} <1>
    There is exactly one item!
  {#is > 10} <2>
    There are more than 10 items!
  {#else} <3>
    There are 2 -10 items!
{/when}
----

Following operators can be used either in `when` and `switch`: `not, ne, !=`, `gt, >`, `ge, >=`, `lt, <`, `le, \<=`, `in`, `ni, !in`.
// end::update_22_3[]

*Message Bundling*

// tag::update_20_5[]

[source, java]
----
@io.quarkus.qute.i18n.MessageBundle 
public interface AppMessages {
    @io.quarkus.qute.i18n.Message("Hello {name}!") 
    String hello_name(String name); 
}
----

There are 3 methods to inject the message:

[source, java]
----
MessageBundles.get(AppMessages.class).hello_name("Lucie");
----

or

[source, java]
----
@Inject AppMessages app;

app.hello_name("Lucie");
----

or

[source, html]
----
<p>{msg:hello_name('Lucie')}</p>
----

*Localization*

There are two ways to set localized message:

[source, java]
----
@io.quarkus.qute.i18n.Localized("de") 
public interface GermanAppMessages {

    @Override
    @io.quarkus.qute.i18n.Message("Hallo {name}!") 
    String hello_name(String name);
}
----

or

[source, properties]
.msg_de.properties
----
hello_name=Hallo {name}!
----
// end::update_20_5[]

You can render programmaticaly the templates too:

[source, java]
----

// file located at src/main/resources/templates/reports/v1/report_01.{}
@ResourcePath("reports/v1/report_01")
Template report;

String output = report
    .data("samples", service.get())
    .render();
----
// end::update_12_8[]

*Value Resolvers*

// tag::update_23_1[]
Value resolvers are invoked when evaluating expressions.

[source, java]
----
void configureEngine(@Observes EngineBuilder builder) {
  builder.addValueResolver(ValueResolver.builder()
      .appliesTo(ctx -> ctx.getBase() instanceof Long && ctx.getName().equals("tenTimes"))
      .resolveSync(ctx -> (Long) ctx.getBase() * 10)
      .build());
}
----
// end::update_23_1[]

*Content Filters*

// tag::update_23_2[]
Content filters can be used to modify the template contents before parsing.

[source, java]
----
void configureEngine(@Observes EngineBuilder builder) {
  builder.addParserHook(new ParserHook() {
      @Override
      public void beforeParsing(ParserHelper parserHelper) {
          parserHelper.addContentFilter(contents -> contents.replace("${", "$\\{"));
      }
  });
}
----
// end::update_23_2[]

*Reactive and Async*

// tag::update_14_13[]
[source, java]
----
CompletionStage<String> async = report.renderAsync();
Multi<String> publisher = report.createMulti();

Uni<String> content = io.smallrye.mutiny.Uni.createFrom()
                            .completionStage(() -> report.renderAsync());
----
// end::update_14_13[]

*Qute Mail Integration*
// tag::update_13_1[]
[source, java]
----
@Inject
MailTemplate hello;

CompletionStage<Void> c = hello.to("to@acme.org")
     .subject("Hello from Qute template")
     .data("name", "John")
     .send();
----

INFO: Template located at `src/main/resources/templates/hello.[html|txt]`.
// end::update_13_1[]

== Sentry
// tag::update_12_10[]

Quarkus integrates with https://sentry.io[Sentry] for logging errors into an error monitoring system.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-logging-sentry"
----

And the configuration to send all errors occuring in the package `org.example` to Sentrty with DSN `https://abcd@sentry.io/1234`:

[source, properties]
----
quarkus.log.sentry=true
quarkus.log.sentry.dsn=https://abcd@sentry.io/1234
quarkus.log.sentry.level=ERROR
quarkus.log.sentry.in-app-packages=org.example
----

Full list of configuration properties having  `quarkus.log` as prefix:

`sentry.enable`::
Enable the Sentry logging extension (default: false)

`sentry.dsn`::
Where to send events.

`sentry.level`::
Log level (default: `WARN`)

`sentry.server-name`::
Sets the server name that will be sent with each event.

`sentry.in-app-packages`::
Configure which package prefixes your application uses.
// end::update_12_10[]

== JSch
// tag::update_13_2[]

Quarkus integrates with http://www.jcraft.com/jsch/[Jsch] for SSH communication.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-jsch"
----

[source, java]
----
JSch jsch = new JSch();
Session session = jsch.getSession(null, host, port);
session.setConfig("StrictHostKeyChecking", "no");
session.connect();
----
// end::update_13_2[]

== Cache
// tag::update_13_17[]

Quarkus can cache method calls by using as key the tuple (method + arguments).

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="cache"
----

[source, java]
----
@io.quarkus.cache.CacheResult(cacheName = "weather-cache")
public String getDailyForecast(LocalDate date, String city) {}
----

`@CacheInvalidate` removes the element represented by the calculated cache key from cache.
`@CacheInvalidateAll` removes all entries from the cache.
`@CacheKey` to specifically set the arguments to be used as key instead of all.

[source, java]
----
@ApplicationScoped
public class CachedBean {

    @CacheResult(cacheName = "foo")
    public Object load(Object key) {}

    @CacheInvalidate(cacheName = "foo")
    public void invalidate(Object key) {}

    @CacheInvalidateAll(cacheName = "foo")
    public void invalidateAll() {}
}
----

// tag::update_19_1[]
You can disable the caching system by setting `quarkus.cache.enabled` property to `false`.
// end::update_19_1[]

This extension uses https://github.com/ben-manes/caffeine[Caffeine] as its underlying caching provider.

Each cache can be configured individually:

[source, properties]
----
quarkus.cache.caffeine."foo".initial-capacity=10
quarkus.cache.caffeine."foo".maximum-size=20
quarkus.cache.caffeine."foo".expire-after-write
quarkus.cache.caffeine."bar".maximum-size=1000 
----

Full list of configuration properties having  `quarkus.cache.caffeine.[cache-name]` as prefix:

`initial-capacity`::
Minimum total size for the internal data structures.

`maximum-size`::
Maximum number of entries the cache may contain.

`expire-after-write`::
Specifies that each entry should be automatically removed from the cache once a fixed duration has elapsed after the entry's creation, or last write.

`expire-after-access`::
Specifies that each entry should be automatically removed from the cache once a fixed duration has elapsed after the entry's creation, or last write.
// end::update_13_17[]

// tag::update_14_3[]
TIP: You can multiple cache annotations on a single method.
// end::update_14_3[]

// tag::update_16_4[]
If you see a `javax.enterprise.context.ContextNotActiveException`, you need to add the `quarkus-smallrye-context-propagation` extension.
// end::update_16_4[]

== Banner

// tag::update_14_9[]
Banner is printed by default.
It is not an extension but placed in the core.

`quarkus.banner.path`::
 Path is relative to root of the classpath. (default: `default_banner.txt`)

 `quarkus.banner.enabled`::
Enables banner. (default : `true`)
// end::update_14_9[]

== OptaPlanner

// tag::update_14_35[]
Quarkus integrates with https://www.optaplanner.org/[OptaPlanner].

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-optaplanner, quarkus-optaplanner-jackson"
----

[source, java]
----
@PlanningSolution
public class TimeTable {
}

@Inject
private SolverManager<TimeTable, UUID> solverManager;

UUID problemId = UUID.randomUUID();
SolverJob<TimeTable, UUID> solverJob = solverManager.solve(problemId, problem);
TimeTable solution = solverJob.getFinalBestSolution();
----

Possible configuration options prefixed with `quarkus.optaplanner`:

`solver-config-xml`::
A classpath resource to read the solver configuration XML. Not mandatory.

`solver.environment-mode`::
Enable runtime assertions to detect common bugs in your implementation during development. Possible values: `FAST_ASSERT`, `FULL_ASSERT`, `NON_INTRUSIVE_FULL_ASSERT`, `NON_REPRODUCIBLE`, `REPRODUCIBLE`. (default: `REPRODUCIBLE`)

`solver.move-thread-count`::
Enable multithreaded solving for a single problem. Possible values: `MOVE_THREAD_COUNT_NONE`, `MOVE_THREAD_COUNT_AUTO`, a number or formula based on the available processors. (default: `MOVE_THREAD_COUNT_NONE`)

`solver.termination.spent-limit`::
How long the solver can run. (ie `5s`)

`solver.termination.unimproved-spent-limit`::
How long the solver can run without finding a new best solution after finding a new best solution. (ie `2h`)

`solver.termination.best-score-limit`::
Terminates the solver when a specific or higher score has been reached. (ie `0hard/-1000soft`)

`solver-manager.parallel-solver-count`::
The number of solvers that run in parallel. (default: `PARALLEL_SOLVER_COUNT_AUTO`)
// end::update_14_35[]

== Context Propagation

// tag::update_14_36[]
[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-smallrye-context-propagation"
----

If using `mutiny` extension together you already get context propagation for ArC, RESTEasy and transactions.
With `CompletionStage` you need to:

[source, java]
----
@Inject ThreadContext threadContext;
@Inject ManagedExecutor managedExecutor;

threadContext.withContextCapture(..)
             .thenApplyAsync(r -> {}, managedExecutor);
----

If you are going to use security in a reactive environment you will likely need Smallrye Content Propagation to propagate the identity throughout the reactive callback.
// end::update_14_36[]

== Configuration from HasiCorp Consul

// tag::update_16_13[]
You can read runtime configuration from HashiCorp Consul.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="consul-config"
----

You need to configure Consul:

[source, properties]
----
quarkus.consul-config.enabled=true
quarkus.consul-config.agent.host-port=localhost:8500
quarkus.consul-config.properties-value-keys=config/consul-test
----

[source, java]
----
@ConfigProperty(name = "greeting.message")
String message;
----

In Consul:

[source, json]
----
"Key": "config/consul-test",
"Value": "greeting.message=Hello from Consul"
----

Possible configuration parameters, prefixed with `quarkus.consul-config`:

`enabled`::
The application will attempt to look up the configuration from Consul. (default: `false`)

`prefix`::
Common prefix that all keys share when looking up the keys from Consul. 
The prefix is *not* included in the keys of the user configuration

raw-value-keys::
Keys whose value is a raw string.
The keys that end up in the user configuration are the keys specified her with '/' replaced by '.'

`properties-value-keys`::
Keys whose value represents a properties-like file conttent.

`fail-on-missing-key`::
If the application will not start if any of the configured config sources cannot be located. (default: `true`)

// tag::update_17_8[]
`trust-store`::
TrustStore to be used containing the SSL certificate used by Consul agent.

`trust-store-password`::
Password of TrustStore to be used containing the SSL certificate used by Consul agent.

`key-password`::
Password to recover key from KeyStore for SSL client authentication with Consul agent.
// end::update_17_8[]

`agent.host-port`::
Consul agent host. (default: `localhost:8500`)

`agent.use-https`::
Use HTTPS when communicating with the agent. (default: `false`)

`agent.token`::
Consul token to be provided when authentication is enabled.

`agent.key-store`::
KeyStore (classpath or filesystem) to be used containing the SSL certificate used by Consul agent.

`agent.key-store-password`::
Password of KeyStore.

`agent.trust-certs`::
To trust all certificates or not.

`agent.connection-timeout`::
Connection timeout. (default: `10S`)

`agent.read-timeout`::
Reading timeout. (default: `60S`)
// end::update_16_13[]

== Amazon Alexa

// tag::update_15_13[]
You can use Amazon Alexa by adding the extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-amazon-alexa"
----
// end::update_15_13[]

== WebJar Locator

// tag::update_16_18[]
To change how you can refer to webjars skipping the version part you can use WebJars locator extension.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="webjars-locator"
----

Then the JavaScript location is changed from `/webjars/jquery/3.1.1/jquery.min.js` to `/webjars/jquery/jquery.min.js` in your HTML files.
// end::update_16_18[]

== Amazon SES

// tag::update_16_24[]
[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="amazon-ses"
----

[source, java]
----
@Inject
software.amazon.awssdk.services.ses.SesClient sesClient;

@Inject
software.amazon.awssdk.services.ses.SesAsyncClient sesClient;
----

[source,properties]
----
quarkus.ses.endpoint-override=http://localhost:8012
quarkus.ses.aws.region=us-east-1
quarkus.ses.aws.credentials.type=static
quarkus.ses.aws.credentials.static-provider.access-key-id=test-key
quarkus.ses.aws.credentials.static-provider.secret-access-key=test-secret
----

You need to set a HTTP client either `URL Connection`:

[source, xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>url-connection-client</artifactId>
</dependency>
----

or Apache HTTP:

[source, xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>apache-client</artifactId>
</dependency>
----

[source, properties]
----
quarkus.ses.sync-client.type=apache
----

Or async:

[source, xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>netty-nio-client</artifactId>
</dependency>
----

Configuration properties are the same as <<Amazon DynamoDB>> but changing the prefix from `dynamodb` to `ses`.
// end::update_16_24[]


== Jbang

// tag::update_19_6[]
Creating an initial script:

[source, bash]
----
jbang scripting/quarkusapp.java
----

Adding Quarkus dependencies in script:

[source, bash]
----
//DEPS io.quarkus:quarkus-resteasy:{quarkus-version}
----

Put some Quarkus CLI code:

[source, java]
----
@Path("/hello")
@ApplicationScoped
public class quarkusapp {
    @GET
    public String sayHello() {
        return "hello";
    }
    public static void main(String[] args) {
        Quarkus.run(args);
    }
}
----

To run the script:

[source, bash]
----
jbang quarkusapp.java
----
// end::update_19_6[]

// tag::update_22_6[]
A Maven goal is provided to scaffold a project:

[source, bash]
----
mvn io.quarkus:quarkus-maven-plugin:<version>:create-jbang
----
// end::update_22_6[]