== Apache Camel
// tag::update_2_1[]
Apache Camel Quarkus has its own site: https://github.com/apache/camel-quarkus
// end::update_2_1[]

== WebSockets
// tag::update_2_2[]
Quarkus can be used to handling web sockets.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-undertow-websockets"
----

And web sockets classes can be used:

[source, java]
----
@ServerEndpoint("/chat/{username}")
@ApplicationScoped
public class ChatSocket {

    @OnOpen
    public void onOpen(Session session, 
                @PathParam("username") String username) {}

    @OnClose
    public void onClose(..) {}

    @OnError
    public void onError(..., Throwable throwable) {}

    @OnMessage
    public void onMessage(...) {}

}
----
// end::update_2_2[]

== OpenAPI
// tag::update_2_3[]
Quarkus can expose its API description as https://swagger.io/specification/[OpenAPI, window="_blank"] spec and test it using https://swagger.io/tools/swagger-ui/[Swagger UI, window="_blank"].

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-smallrye-openapi"
----

Then you only need to access to `/openapi` to get OpenAPI v3 spec of services.

// tag::update_3_5[]
You can update the OpenApi path by setting `quarkus.smallrye-openapi.path` property.
// end::update_3_5[]

Also, in case of starting Quarkus application in `dev` or `test` mode, Swagger UI is accessible at `/swagger-ui`.
If you want to use it in production mode you need to set `quarkus.swagger-ui.always-include` property to `true`.

You can update the Swagger UI path by setting `quarkus.swagger-ui.path` property.

[source, properties]
----
quarkus.swagger-ui.path=/my-custom-path
----
// end::update_2_3[]

// tag::update_6_6[]
You can customize the output by using Open API v3 annotations.

[source, java]
----
@Schema(name="Developers", 
        description="POJO that represents a developer.")
public class Developer {
    @Schema(required = true, example = "Alex")
    private String name;
}

@POST
@Path("/developer")
@Operation(summary = "Create deeloper",
           description = "Only be done by admin.")
public Response createDeveloper(
        @RequestBody(description = "Developer object", 
            required = true,
            content = @Content(schema = 
            @Schema(implementation = Developer.class))) 
                Developer developer)
----

All possible annotations can be seen at https://github.com/eclipse/microprofile-open-api/tree/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations[org.eclipse.microprofile.openapi.annotations, window="_blank"] package.
// end::update_6_6[]

// tag::update_8_10[]
You can also serve OpenAPI Schema from static files instead of dynamically generated from annotation scanning.

You need to put OpenAPIdocumentation under `META-INF` directory (ie: `META-INF/openapi.yaml`).

A request to `/openapi` will serve the combined OpenAPI document from the static file and the generated from annotations.
You can disable the scanning documents by adding the next configuration property: `mp.openapi.scan.disable=true`.

Other valid document paths are: `META-INF/openapi.yml`, `META-INF/openapi.json`, `WEB-INF/classes/META-INF/openapi.yml`, `WEB-INF/classes/META-INF/openapi.yaml`, `WEB-INF/classes/META-INF/openapi.json`.
// end::update_8_10[]

== Mail Sender
// tag::update_2_5[]
You can send emails by using Quarkus Mailer extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-mailer"
----

You can inject two possible classes `io.quarkus.mailer.Mailer` for synchronous API or `io.quarkus.mailer.reactive.ReactiveMailer` for asynchronous/reactive API.

[source, java]
----
@Inject
Mailer mailer;
----

And then you can use them to send an email:

[source, java]
----
mailer.send(
    Mail.withText("to@acme.org", "Subject", "Body")
);
----

*Reactive Mail client*

// tag::update_14_14[]
[source, java]
----
@Inject
ReactiveMailer reactiveMailer;

CompletionStage<Response> stage = 
    reactiveMailer.send(
        Mail.withText("to@acme.org", "Subject", "Body")
    )
    .subscribeAsCompletionStage()
    .thenApply(x -> Response.accepted().build());
----

TIP: If you are using `quarkus-resteasy-mutiny`, you can return `io.smallrye.mutiny.Uni` type.

// end::update_14_14[]
`Mail` class contains methods to add `cc`, `bcc`, `headers`, `bounce address`, `reply to`, `attachments`, `inline attachments` and `html body`.

[source, java]
----
mailer.send(Mail.withHtml("to@acme.org", "Subject", body)
      .addInlineAttachment("quarkus.png",
            new File("quarkus.png"),
            "image/png", "<my-image@quarkus.io>"));
----

TIP: If you need deep control you can inject Vert.x mail client `@Inject  MailClient client;`

You need to configure SMTP properties to be able to send an email:

[source, properties]
----
quarkus.mailer.from=test@quarkus.io
quarkus.mailer.host=smtp.sendgrid.net
quarkus.mailer.port=465
quarkus.mailer.ssl=true
quarkus.mailer.username=....
quarkus.mailer.password=....
----

List of Mailer parameters.
`quarkus.` as a prefix is skipped in the next table.

|===	
|Parameter | Default | Description

a|`mailer.from`
|
a|Default address.

a|`mailer.mock`
a|false in `prod`, true in `dev` and `test`.
|Emails not sent, just printed and stored in a `MockMailbox`.

a|`mailer.bounce-address`
|
|Default address.

a|`mailer.host`
a|_mandatory_
|SMTP host.

a|`mailer.port`
|25
|SMTP port.

a|`mailer.username`
|
|The username.

a|`mailer.password`
|
|The password.

a|`mailer.ssl`
a|`false`
|Enables SSL.

a|`mailer.trust-all`
|false
|Trust all certificates.

a|`mailer.max-pool-size`
|10
|Max open connections .

a|`mailer.own-host-name`
|
a|Hostname for `HELO/EHLO` and `Message-ID`

a|`mailer.keep-alive`
a|`true`
|Connection pool enabled.

a|`mailer.disable-esmtp`
a|`false`
|Disable ESMTP.

a|`mailer.start-tls`
a|`OPTIONAL`
a|TLS security mode. `DISABLED`, `OPTIONAL`, `REQUIRED`.

a|`mailer.login`
a|`NONE`
a|Login mode. `NONE`, `OPTIONAL`, `REQUIRED`.

a|`mailer.auth-methods`
|All methods.
|Space-separated list.

a|`mailer.key-store`
|
|Path of the key store.

a|`mailer.key-store-password`
|
|Key store password.
|===
// tag::update_3_7[]
// tag::update_6_x[]
IMPORTANT: if you enable SSL for the mailer and you want to build a native executable, you will need to enable the SSL support `quarkus.ssl.native=true`. 
// end::update_6_x[]

*Testing*

If `quarkus.mailer.mock` is set to `true`, which is the default value in `dev` and `test` mode, you can inject `MockMailbox` to get the sent messages.

[source, java]
----
@Inject
MockMailbox mailbox;

@BeforeEach
void init() {
    mailbox.clear();
}

List<Mail> sent = mailbox
                    .getMessagesSentTo("to@acme.org");
----
// end::update_3_7[]

// end::update_2_5[]

== Scheduled Tasks
// tag::update_3_2[]
You can schedule periodic tasks with Quarkus.

[source, java]
----
@ApplicationScoped
public class CounterBean {

    @Scheduled(every="10s")
    void increment() {}

    @Scheduled(cron="0 15 10 * * ?")
    void morningTask() {}
}
----

`every` and `cron` parameters can be surrounded with `{}` and the value is used as config property to get the value. 

[source java]
----
@Scheduled(cron = "{morning.check.cron.expr}")
void morningTask() {}
----

And configure the property into `application.properties`:

[source, properties]
----
morning.check.cron.expr=0 15 10 * * ?
----
// end::update_3_2[]

// tag::update_12_5[]
By default Quarkus expresion is used, but you can change that by setting `quarkus.scheduler.cron-type` property.

[source, properties]
----
quarkus.scheduler.cron-type=unix
----
// end::update_12_5[]

// tag::update_14_18[]
`org.quartz.Scheduler` can be injected as any other bean and scehdule jobs programmatically.

[source, java]
----
@Inject
org.quartz.Scheduler quartz;

quartz.scheduleJob(job, trigger);
----
// end::update_14_18[]

== Kogito
// tag::update_3_9[]
Quarkus integrates with http://www.kiegroup.org/[Kogito, window="_blank"], a next-generation business automation toolkit from Drools and jBPM projects for adding business automation capabilities.

To start using it you only need to add the next extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="kogito"
----
// end::update_3_9[]

== Apache Tika
// tag::update_5_8[]

Quarkus integrets with https://tika.apache.org/[Apache Tika, window="_blank"] to detect and extract metadata/text from different file types:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-tika"
----

[source, java]
----
@Inject
io.quarkus.tika.TikaParser parser;

@POST
@Path("/text")
@Consumes({ "text/plain", "application/pdf", 
            "application/vnd.oasis.opendocument.text" })
@Produces(MediaType.TEXT_PLAIN)
public String extractText(InputStream stream) {
    return parser.parse(stream).getText();
}
----

// tag::update_7_3[]
You can configure Apache Tika in `application.properties` file by using next properties prefixed with `quarkus`:

|===	
|Parameter | Default | Description

a|`tika.tika-config-path`
a|`tika-config.xml`
a|Path to the Tika configuration resource. 

a|`quarkus.tika.parsers`
a|
a|CSV of the abbreviated or full parser class to be loaded by the extension.

a|`tika.append-embedded-content`
a|`true`
a|The document may have other embedded documents. Set if autmatically append.
|===
// end::update_7_3[]
// end::update_5_8[]

== JGit
// tag::update_8_1[]

Quarkus integrets with https://www.eclipse.org/jgit/[JGit, window="_blank"] to integrate with Git repositories:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-jgit"
----

And then you can start using JGit:

[source, java]
----
try (Git git = Git.cloneRepository()
                  .setDirectory(tmpDir)
                  .setURI(url)
                  .call()) {
    return tmpDir.toString();
}
----

IMPORTANT: When running in native mode, make sure to configure SSL access correctly `quarkus.ssl.native=true` (https://quarkus.io/guides/native-and-ssl-guide[Native and SSL, window="_blank"]). 
// end::update_8_1[]

== Web Resources

// tag::update_8_9[]
You can serve web resources with Quarkus.
You need to place web resources at `src/main/resources/META-INF/resources` and then they are accessible (ie http://localhost:8080/index.html)
// end::update_8_9[]

// tag::update_9_6[]
By default static resources as served under the root context.
You can change this by using `quarkus.http.root-path` property.
// end::update_9_6[]

== Transactional Memory

// tag::update_10_6[]
Quarkus integrates with the Software Transactional Memory (STM) implementation provided by the https://narayana.io/docs/project/index.html[Narayana] project.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="narayana-stm"
----

Transactional objects must be interfaces and annotated with `org.jboss.stm.annotations.Transactional`.

[source, java]
----
@Transactional
@NestedTopLevel
public interface FlightService {
    int getNumberOfBookings();
    void makeBooking(String details);
}
----

The pessimistic strategy is the default one, you can change to optimistic by using `@Optimistic`.

Then you need to create the object inside `org.jboss.stm.Container`.

[source, java]
----
Container<FlightService> container = new Container<>(); 
FlightServiceImpl instance = new FlightServiceImpl(); 
FlightService flightServiceProxy = container.create(instance);
----

The implementation of the service sets the locking and what needs to be saved/restored:

[source, java]
----
import org.jboss.stm.annotations.ReadLock;
import org.jboss.stm.annotations.State;
import org.jboss.stm.annotations.WriteLock;

public class FlightServiceImpl 
    implements FlightService {
    @State
    private int numberOfBookings;

    @ReadLock
    public int getNumberOfBookings() {
        return numberOfBookings;
    }

    @WriteLock
    public void makeBooking(String details) {
        numberOfBookings += 1;
    }
}
----

Any member is saved/restored automatically (`@State` is not mandatory).
You can use `@NotState` to avoid behaviour.

*Transaction boundaries*

_Declarative_

 * `@NestedTopLevel`: Defines that the container will create a new top-level transaction for each method invocation.
 * `@Nested`: Defines that the container will create a new top-level or nested transaction for each method invocation.

_Programmatically_

[source, java]
----
AtomicAction aa = new AtomicAction(); 

aa.begin(); 
{
    try {
        flightService.makeBooking("BA123 ...");
        taxiService.makeBooking("East Coast Taxis ..."); 
        
        aa.commit();
    } catch (Exception e) {
        aa.abort(); 
    }
}
----
// end::update_10_6[]

== Quartz
// tag::update_12_2[]
Quarkus integrates with http://www.quartz-scheduler.org/[Quartz]  to schedule periodic clustered tasks.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quartz"
----

[source, java]
----
@ApplicationScoped
public class TaskBean {

    @Transactional
    @Scheduled(every = "10s")
    void schedule() {
        Task task = new Task();
        task.persist();
    }
}
----

To configure in clustered mode vida DataSource:

[source, application.properties]
----
quarkus.datasource.url=jdbc:postgresql://localhost/quarkus_test
quarkus.datasource.driver=org.postgresql.Driver
# ...

quarkus.quartz.clustered=true
quarkus.quartz.store-type=db
----

IMPORTANT: You need to define the datasource used by clustered mode and also import the database tables following the Quartz schema.
// end::update_12_2[]

== Qute

// tag::update_12_8[]
Qute is a templating engine designed specifically to meet the Quarkus needs.
Templates should be placed by default at `src/main/resources/templates` aand subdirectories.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-resteasy-qute"
----

Templates can be defined in any format, in case of HTML:

[source, html]
.item.html
----
{@org.acme.Item item}
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{item.name}</title>
</head>
<body>
    <h1>{item.name}</h1>
    <div>Price: {item.price}</div>
    {#if item.price > 100}
    <div>Discounted Price: {item.discountedPrice}</div>
    {/if}
</body>
</html>
----

First line is not mandatory but helps on doing property checks at compilation time.

To render the template:

[source, java]
----
public class Item {
    public String name;
    public BigDecimal price;
}

@Inject
io.quarkus.qute.Template item;

@GET
@Path("{id}")
@Produces(MediaType.TEXT_HTML)
public TemplateInstance get(@PathParam("id") Integer id) {
    return item.data("item", service.findItem(id));
}

@TemplateExtension
static BigDecimal discountedPrice(Item item) {
    return item.price.multiply(new BigDecimal("0.9"));
}
----

If `@ResourcePath` is not used in `Template` then the name of the field is used as file name.
In this case the file should be `src/main/resources/templates/item.{}`.
Extension of the file is not required to be set.

`discountedPrice` is not a field of the POJO but a method call.
Method definition must be annotated with `@TemplateExtension` and be static method.
First parameter is used to match the base object (`Item`).
// tag::update_13_8[]
`@TemplateExtension` can be used at class level:

[source, java]
----
@TemplateExtension
public class MyExtensions {
    static BigDecimal discountedPrice(Item item) {
        return item.price.multiply(new BigDecimal("0.9"));
    }
}
----

Methods with multiple parameters are supported too:

[source,html]
----
{item.discountedPrice(2)}
----

[source, java]
----
static BigDecimal discountedPrice(Item item, int scale) {
    return item.price.multiply(scale);
}
----
// end::update_13_8[]

// tag::update_14_4[]
Qute `for` syntax supports any instance of `Iterable`, `Map.EntrySet`, `Stream` or `Integer`.

[source, html]
----
{#for i in total}
  {i}:
{/for}
----
// end::update_14_4[]

// tag::update_14_27[]
The next map methods are supported:

[source, html]
----
{#for key in map.keySet}
{#for value in map.values}
{map.size}
{#if map.isEmpty}
{map['foo']
----

The next list methods are supported:

[source, html]
----
{list[0]}
----

The next number methods are supported:

[source, html]
----
{#if counter.mod(5) == 0}
----
// end::update_14_27[]

You can render programmaticaly the templates too:

[source, java]
----

// file located at src/main/resources/templates/reports/v1/report_01.{}
@ResourcePath("reports/v1/report_01")
Template report;

String output = report
    .data("samples", service.get())
    .render();
----
// end::update_12_8[]

*Reactive and Async*

// tag::update_14_13[]
[source, java]
----
CompletionStage<String> async = report.renderAsync();
Publisher<String> publisher = report.publisher();

Uni<String> content = io.smallrye.mutiny.Uni.createFrom()
                            .completionStage(() -> report.renderAsync());
----
// end::update_14_13[]

*Qute Mail Integration*
// tag::update_13_1[]
[source, java]
----
@Inject
MailTemplate hello;

CompletionStage<Void> c = hello.to("to@acme.org")
     .subject("Hello from Qute template")
     .data("name", "John")
     .send();
----

INFO: Template located at `src/main/resources/templates/hello.[html|txt]`.
// end::update_13_1[]

== Sentry
// tag::update_12_10[]

Quarkus integrates with https://sentry.io[Sentry] for logging errors into an error monitoring system.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-logging-sentry"
----

And the configuration to send all errors occuring in the package `org.example` to Sentrty with DSN `https://abcd@sentry.io/1234`:

[source, properties]
----
quarkus.log.sentry=true
quarkus.log.sentry.dsn=https://abcd@sentry.io/1234
quarkus.log.sentry.level=ERROR
quarkus.log.sentry.in-app-packages=org.example
----

Full list of configuration properties having  `quarkus.log` as prefix:

`sentry.enable`::
Enable the Sentry logging extension (default: false)

`sentry.dsn`::
Where to send events.

`sentry.level`::
Log level (default: `WARN`)

`sentry.in-app-packages`::
Configure which package prefixes your application uses.
// end::update_12_10[]

== JSch
// tag::update_13_2[]

Quarkus integrates with http://www.jcraft.com/jsch/[Jsch] for SSH communication.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-jsch"
----

[source, java]
----
JSch jsch = new JSch();
Session session = jsch.getSession(null, host, port);
session.setConfig("StrictHostKeyChecking", "no");
session.connect();
----
// end::update_13_2[]

== Cache
// tag::update_13_17[]

Quarkus can cache method calls by using as key the tuple (method + arguments).

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="cache"
----

[source, java]
----
@io.quarkus.cache.CacheResult(cacheName = "weather-cache")
public String getDailyForecast(LocalDate date, String city) {}
----

`@CacheInvalidate` removes the element represented by the calculated cache key from cache.
`@CacheInvalidateAll` removes all entries from the cache.
`@CacheKey` to specifically set the arguments to be used as key instead of all.

[source, java]
----
@ApplicationScoped
public class CachedBean {

    @CacheResult(cacheName = "foo")
    public Object load(Object key) {}

    @CacheInvalidate(cacheName = "foo")
    public void invalidate(Object key) {}

    @CacheInvalidateAll(cacheName = "foo")
    public void invalidateAll() {}
}
----

This extension uses https://github.com/ben-manes/caffeine[Caffeine] as its underlying caching provider.

Each cache can be configured individually:

[source, properties]
----
quarkus.cache.caffeine."foo".initial-capacity=10
quarkus.cache.caffeine."foo".maximum-size=20
quarkus.cache.caffeine."foo".expire-after-write
quarkus.cache.caffeine."bar".maximum-size=1000 
----

Full list of configuration properties having  `quarkus.cache.caffeine.[cache-name]` as prefix:

`initial-capacity`::
Minimum total size for the internal data structures.

`maximum-size`::
Maximum number of entries the cache may contain.

`expire-after-write`::
Specifies that each entry should be automatically removed from the cache once a fixed duration has elapsed after the entry's creation, or last write.

`expire-after-access`::
Specifies that each entry should be automatically removed from the cache once a fixed duration has elapsed after the entry's creation, or last write.
// end::update_13_17[]

// tag::update_14_3[]
TIP: You can multiple cache annotations on a single method.
// end::update_14_3[]

== Banner

// tag::update_14_9[]
To print a Quarkus banner at start-up:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="banner"
----

Configure banner by setting `quarkus.banner.path` to a _txt_ file containing the banner. Path is relative to root of the classpath.
// end::update_14_9[]