== HTTP Configuration
// tag::update_16_11[]

You can configure HTTP parameters.
Using `quarkus.http` prefix:

`cors`::
Enable CORS. (default: `false`)

`cors.origins`::
CSV of origins allowed. (dedault: Any request valid.)

`cors.methods`::
CSV of methods valid. (default: Any method valid.)

`cors.headers`::
CSV of valid allowed headers. (default: Any requested header valid.)

`cors.exposed-headers`::
CSV of valid exposed headers.

`port`::
The HTTP port. (default: `8080`)

`test-port`::
The HTTP test port. (default: `8081`)

`host`::
The HTTP host. (default: `0.0.0.0`)

`host-enabled`::
Enable listening to host:port. (default: `true`)

`ssl-port`::
The HTTPS port. (default `8443`)

`test-ssl-port`::
The HTTPS port used to run tests. (default `8444`)

`proxy-address-forwarding`::
The address, scheme etc will be set from headers forwarded by the proxy server.

`allow-forwarded`::
Proxy address forwarding is enabled then the standard `Forwarded` header will be used, rather than the more common but not standard `X-Forwarded-For`.

`insecure-requests`::
If insecure requests are allowed. Possible values: `enabled`, `redirect`, `disable`. (default: `enabled`)

`http2`::
Enables HTTP/2. (default: `true`)

`ssl.port`::
The _HTTPS_ port. (default: `8443`)

`ssl.certificate.file`::
The file path to a service certificate or certificate chain in _PEM_ format. Relative to `src/main/resources`.

`ssl.certificate.key-file`::
The file path to the corresponding certificate private key in _PEM_ format. Relative to `src/main/resources`.

`ssl.certificate.key-store-file`::
The key store contains the certificate information. Relative to `src/main/resources`.

`ssl.certificate.key-store-file-type`::
The key store type. It is automatically detected based on the file name or can be set manually. Supported values are: `JKS`, `JCEKS`, `P12`, `PKCS12` or `PFX`.

`ssl.certificate.key-store-password`::
The password to open the key store file.

`ssl.certificate.trust-store-file`
The trust store location which contains the certificate information of the certificates to trust. Relative to `src/main/resources`.

`ssl.certificate.trust-store-file-type`::
The trust store type. It is automatically detected based on the file name or can be set manually.

`ssl.certificate.trust-store-password`::
The password to open the trust store file.

`ssl.cipher-suites`::
A list of strings of cipher suites to use. If not provided, a reasonable default is selected.

`ssl.protocols`::
The list of protocols to explicitly enable. (default: `TLSv1.3` and `TLSv1.2`).

`ssl.client-auth`::
Configures the engine to require/request client authentication. Possible values are: `none`, `request` and  `required`. (default:  `none`).

`io-threads`::
The number if IO threads used to perform IO.

`limits.max-header-size`::
The maximum length of all headers. (default: `20k`)

`limits.max-body-size`::
The maximum size of a request body. (default: `no-limit`)

`limits.max-chunk-size`::
The max HTTP chunk size

`idle-timeout`::
Http connection idle timeout. (default: `30M`)

`read-timeout`::
Http connection read timeout for blocking IO. (default: `60s`)

`body.handle-file-uploads`::
If the files sent using `multipart/form-data` will be stored locally. (default: `true`)

`body.uploads-directory`::
The directory where the files sent using `multipart/form-data` should be stored. (default: `file-uploads`)

`body.merge-from-attributes`::
If the form attributes should be added to the request parameters. (default: `true`)

`body.delete-uploaded-files-on-end`::
If the uploaded files should be removed after serving the request.

`body.preallocate-body-buffer`::
If the body buffer should pre-allocated based on the `Content-Length` header value. (default: `1K`)

`auth.session.encryption-key`::
The encryption key that is used to store persistent logins.

`so-reuse-port`::
Enable socket reuse port.

`tcp-quick-ack`::
Enable tcp quick ack.

`tcp-cork`::
Enable tcp cork.

`tcp-fast-open`::
Enable tcp fast open.

`domain-socket`::
Path to a unix domain socket. (default: `/var/run/io.quarkus.app.socket`)

`domain-socket-enabled`::
Enables domain socket.

`record-request-start-time`::
If enabled then start time will be recorded to enable logging of total request time. (default: `false`)

`access-log.enabled`::
If access logging is enabled. (default: `false`)

`access-log.pattern`::
The access log pattern. (default: `common`)

`access-log.log-to-file`::
If logging should be done to a separate file. (default: `false`)

`access-log.base-file-name`::
The access log file base name. (default: `quarkus`)

`access-log.log-directory`::
The log directory to use when logging access to a file.

`access-log.log-directory`::
The log directory to use when logging access to a file.

`access-log.log-suffix`::
The log file suffix. (default: `.log`)

`access-log.category`::
The log category to use if logging is being done via the standard log mechanism. (default: `io.quarkus.http.access-log`)

`access-log.rotate`::
If the log should be rotated daily. (default: `true`)

`same-site-cookie.<name>.case-sensitive`::
If the cookie pattern is case sensitive.

`same-site-cookie.<name>.value`::
The value to set in the samesite attribute.

`same-site-cookie.<name>.enable-client-checker`::
Some User Agents break when sent SameSite=None, this will detect them and avoid sending the value. (default: `true`)

`same-site-cookie.<name>.add-secure-for-none`::
If this is true then the 'secure' attribute will automatically be sent on cookies with a SameSite attribute of None. (default: `true`)
// end::update_16_11[]

== JAX-RS
// tag::update_4_1[]
Quarkus uses JAX-RS to define https://github.com/jax-rs[REST-ful web APIs, window="_blank"].
// tag::update_10_1[]
Under the covers, Rest-EASY is working with Vert.X directly without using any Servlet.

It is *important* to know that if you want to use any feature that implies a `Servlet` (ie Servlet Filters) then you need to add the `quarkus-undertow` extension to switch back to the `Servlet` ecosystem but generally speaking, you don't need to add it as everything else is well-supported.
// end::update_10_1[]

[source, java]
----
@Path("/book")
public class BookResource {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<Book> getAllBooks() {}

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    public Response createBook(Book book) {}

    @DELETE
    @Path("{isbn}")
    @Produces(MediaType.APPLICATION_JSON)
    public Response deleteBook(
        @PathParam("isbn") String isbn) {}
    

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("search")
    public Response searchBook(
        @QueryParam("description") String description) {}
}
----

To get information from request:

`@PathParam`::
Gets content from request URI. (example: `/book/{id} @PathParam("id")`)

`@QueryParam`::
Gets query parameter. (example: `/book?desc="" @QueryParam("desc)`)

`@FormParam`::
Gets form parameter.

`@MatrixParam`::
Get URI matrix parameter. (example: `/book;author=mkyong;country=malaysia`)

`@CookieParam`::
Gets cookie param by name.

`@HeaderParam`::
Gets header parameter by name.

Valid HTTP method annotations provided by the spec are: `@GET`, `@POST`, `@PUT`, `@DELETE`, `@PATCH`, `@HEAD` and `@OPTIONS`.

You can create new annotations that bind to HTTP methods not defined by the spec.

[source, java]
----
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@HttpMethod("LOCK")
public @interface LOCK {
}

@LOCK
public void lockIt() {}
}
----

*Injecting*

Using `@Context` annotation to inject JAX-RS and Servlet information.

[source, java]
----
@GET
public String getBase(@Context UriInfo uriInfo) {
    return uriInfo.getBaseUri();
}
----

Possible injectable objects: `SecurityContext`, `Request`, `Application`, `Configuration`, `Providers`, `ResourceContext`, `ServletConfig`, `ServletContext`, `HttpServletRequest`, `HttpServletResponse`, `HttpHeaders`, `Urinfo`, `SseEventSink` and `Sse`.
// end::update_4_1[]

*HTTP Filters*

// tag::update_3_3[]
HTTP request and response can be intercepted to manipulate the metadata (ie headers, parameters, media type, ...) or abort a request.
You only need to implement the next `ContainerRequestFilter` and `ContainerResponseFilter` JAX-RS interfaces respectively.

[source, java]
----
@Provider
public class LoggingFilter 
        implements ContainerRequestFilter {

    @Context
    UriInfo info;

    @Context
    HttpServletRequest request;

    @Override
    public void filter(ContainerRequestContext context) {
        final String method = context.getMethod();
        final String path = info.getPath();
        final String address = request.getRemoteAddr();
        System.out.println("Request %s %s from IP %s", 
                method, path, address);
    }

}
----
// end::update_3_3[]

*Exception Mapper*

// tag::update_5_1[]
You can map exceptions to produce a custom output by implementing `ExceptionMapper` interface:

[source, java]
----
@Provider
public class ErrorMapper 
    implements ExceptionMapper<Exception> {

    @Override
    public Response toResponse(Exception exception) {
        int code = 500;
        if (exception instanceof WebApplicationException) {
            code = ((WebApplicationException) exception)
                .getResponse().getStatus();
        }
        return Response.status(code)
            .entity(
                Json.createObjectBuilder()
                .add("error", exception.getMessage())
                .add("code", code)
                .build()
            )
            .build();
        }
    }
----
// end::update_5_1[]

*Caching*
// tag::update_13_9[]

Annotations to set Cache-Control headers:

[source, java]
----
@Produces(MediaType.APPLICATION_JSON)
@org.jboss.resteasy.annotations.cache.NoCache
public User me() {}

@Produces(MediaType.APPLICATION_JSON)
@org.jboss.resteasy.annotations.cache.Cache(
    maxAge = 2000,
    noStore = false
)
public User you() {}
----
// end::update_13_9[]

== Vert.X Filters and Routes

// tag::update_9_5[]

*Programmatically*

You can also register Vert.X Filters and Router programmatically inside a CDI bean:

[source, java]
----
import io.quarkus.vertx.http.runtime.filters.Filters;
import io.vertx.ext.web.Router;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;

@ApplicationScoped
public class MyBean {

    public void filters(
            @Observes Filters filters) {
        filters
            .register(
                rc -> {
                    rc.response()
                        .putHeader("X-Filter", "filter 1");
                    rc.next();
                },
                10);
    }

    public void routes(
            @Observes Router router) {
        router
            .get("/")
            .handler(rc -> rc.response().end("OK"));
    }
}
----
// end::update_9_5[]

// tag::update_10_9[]
*Declarative*

You can use `@Route` annotation to use reactive routes and `@RouteFilter` to sue reactive filters in a declarative way:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-vertx-web"
----

[source, java]
----

@ApplicationScoped
public class MyDeclarativeRoutes {
 
    @Route(path = "/hello", methods = HttpMethod.GET)
    public void greetings(RoutingContext rc) {
        String name = rc.request().getParam("name");
        if (name == null) {
            name = "world";
        }
        rc.response().end("hello " + name);
    }

     @RouteFilter(20)
    void filter(RoutingContext rc) {
         rc.response().putHeader("X-Filter", "filter 2");
         rc.next();
    }

}
----
// end::update_10_9[]

== GraphQL

// tag::update_16_12[]
Quarkus integrates with https://graphql.org/[GraphQL] using https://download.eclipse.org/microprofile/microprofile-graphql-1.0.1/microprofile-graphql.html[MicroProfile GraphQL] integration.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="graphql"
----

[source, java]
----
@GraphQLApi
public class FilmResource {

    @Query("allFilms")
    public List<String> films() {
    }

    @Query
    public String getFilm(@Name("filmId") int id)) {} 

    @Query
    public List<Hero> getHeroesWithSurname(
        @DefaultValue("Skywalker") String surname) {
    }

    @Mutation
    public Greetings load(Greetings greetings) {
    }

}
----

If name not provided, then query name is resolved from method name.

You can see the full schema at `/graphql/schema.graphql`.
Also GraphiQL UI is enabled at dev and test mode at `/graphql-ui/`.

Extension can be configured with the follwoing paramters prefixed with `quarkus.smallrye-graphql`.

`root-path`::
The rootPath under which queries will be served. (default: `/graphql`)

`root-path-ui`::
The path where GraphQL UI is available. (default: `/graphql-ui`)

`always-include-ui`::
The path where GraphQL UI is available. (default: `/graphql-ui`)

`root-path-ui`::
Always include the UI. By default this will only be included in dev and test. (default: `false`)

`enable-ui`::
If GraphQL UI should be enabled. (default: `false`)

`metrics.enabled`::
Enable metrics. (default: `false`)
// end::update_16_12[]

== Vert.X Verticle

// tag::update_14_1[]
Vert.X Verticles are also supported:

[source, java]
----
@ApplicationScoped
public class VerticleDeployer {

    @Inject
    Vertx vertx;

    public void init(@Observes StartupEvent ev) {
        CountDownLatch latch = new CountDownLatch(1);
        vertx.deployVerticle(BareVerticle::new, 
            new DeploymentOptions()
                .setConfig(
                    new JsonObject()
                    .put("id", "bare")
                )
            )
            .thenAccept(x -> latch.countDown());
        
        latch.countDown();
    }
}
----

Verticles can be:

bare:: extending `io.vertx.core.AbstractVerticle`.
mutiny:: extendig `io.smallrye.mutiny.vertx.core.AbstractVerticle`.
// end::update_14_1[]

== GZip Support
// tag::update_7_4[]

You can configure Quarkus to use GZip in the `application.properties` file using the next properties with `quarkus.resteasy` suffix:

`gzip.enabled`::
EnableGZip. (default: `false`)

`gzip.max-input`::
Configure the upper limit on deflated request body. (default: `10M`)
// end::update_7_4[]

== GRPC
// tag::update_16_8[]

Quarkus integrates with gRPC:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-grpc"
----

Then you need to configure `build tool` with gRPC plugins. In the case of Maven, the `kr.motd.maven:os-maven-plugin` extension and `org.xolstice.maven.plugins:protobuf-maven-plugin`

Protos files are stored at `src/main/proto`.

When `java` files are created two service implementations are provided: one with default gRPC API and other with Mutiny support.

With `quarkus.grpc.server` prefix, the next configuration properties can be set:

`port`::
The gRPC Server port. (default: `9000`)

`host`::
The gRPC server host. (default: `0.0.0.0`)

`handshake-timeout`::
The gRPC handshake timeout.

`max-inbound-message-size`::
The max inbound message size in bytes.

`plain-text`::
Use plain text. (default: `true`)

`alpn`::
TWhether ALPN should be used. (default: `true`)

`enable-reflection-service`::
Enables the gRPC Reflection Service. (default: `false`)

`ssl.certificate`::
The file path to a server certificate or certificate chain in PEM format.

`ssl.key`::
The file path to the corresponding certificate private key file in PEM format.

`ssl.key-store`::
An optional key store which holds the certificate information instead of specifying separate files.

`ssl.key-store-type`::
An optional parameter to specify the type of the key store file.

`ssl.key-store-password`::
A parameter to specify the password of the key store file. (default: `password`)

`ssl.trust-store`::
Trust store which holds the certificate information of the certificates to trust

`ssl.trust-store-type`::
Parameter to specify type of the trust store file.

`ssl.trust-store-password`::
A parameter to specify the password of the trust store file.

`ssl.cipher-suites`::
A list of the cipher suites to use.

`ssl.protocols`::
The list of protocols to explicitly enable. (default: `TLSv1.3,TLSv1.2`)

`transport-security.certificate`::
The path to the certificate file.

`transport-security.key`::
The path to the private key file.

To consume the service:

[source, java]
----
@GrpcService("hello")
GreeterGrpc.GreeterBlockingStub client;

@GrpcService("hello")
io.grpc.Channel channel;
----

Some configuration example to set the host and the SSL parameters:

[source, properties]
----
quarkus.grpc.clients.hello.host=localhost
quarkus.grpc.clients.hello.plain-text=false
quarkus.grpc.clients.hello.ssl.certificate=src/main/resources/tls/client.pem
quarkus.grpc.clients.hello.ssl.key=src/main/resources/tls/client.key
quarkus.grpc.clients.hello.ssl.trust-store=src/main/resources/tls/ca.pem
----
// end::update_16_8[]

== Fault Tolerance
// tag::update_1_2[]
Quarkus uses https://github.com/eclipse/microprofile-fault-tolerance[MicroProfile Fault Tolerance, window="_blank"] spec:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-smallrye-fault-tolerance"
----

MicroProfile Fault Tolerance spec uses CDI interceptor and it can be used in several elements such as CDI bean, JAX-RS resource or MicroProfile Rest Client.

To do automatic *retries* on a method:

[source, java]
----
@Path("/api")
@RegisterRestClient
public interface WorldClockService {
    @GET @Path("/json/cet/now")
    @Produces(MediaType.APPLICATION_JSON)
    @Retry(maxRetries = 2)
    WorldClock getNow();
}
----

You can set fallback code in case of an error by using `@Fallback` annotation:

[source, java]
----
@Retry(maxRetries = 1)
@Fallback(fallbackMethod = "fallbackMethod")
WorldClock getNow(){}

public WorldClock fallbackMethod() {
    return new WorldClock();
}
----

`fallbackMethod` must have the same parameters and return type as the annotated method.

You can also set logic into a class that implements `FallbackHandler` interface:

[source, java]
----
public class RecoverFallback 
            implements FallbackHandler<WorldClock> {
    @Override
    public WorldClock handle(ExecutionContext context) {
    }
}
----

<<<

And set it in the annotation as value `@Fallback(RecoverFallback.class)`.

In case you want to use *circuit breaker* pattern:

[source, java]
----
@CircuitBreaker(requestVolumeThreshold = 4, 
                failureRatio=0.75, 
                delay = 1000)
WorldClock getNow(){}
----

If 3 `(4 x 0.75)` failures occur among the rolling window of 4 consecutive invocations then the circuit is opened for 1000 ms and then be back to half open.
If the invocation succeeds then the circuit is back to closed again.

You can use *bulkahead* pattern to limit the number of concurrent access to the same resource. 
If the operation is synchronous it uses a semaphore approach, if it is asynchronous a thread-pool one.
When a request cannot be processed `BulkheadException` is thrown.
It can be used together with any other fault tolerance annotation. 

[source, java]
----
@Bulkhead(5)
@Retry(maxRetries = 4, 
       delay = 1000,
       retryOn = BulkheadException.class)
WorldClock getNow(){}
----

Fault tolerance annotations:

|===	
| Annotation | Properties

a|`@Timeout`
a|`unit`

a|`@Retry`
a|`maxRetries`, `delay`, `delayUnit`, `maxDuration`, `durationUnit`, `jitter`, `jitterDelayUnit`, `retryOn`, `abortOn`

a|`@Fallback`
a|`fallbackMethod`

a|`@Bulkhead`
a|`waitingTaskQueue` (only valid in asynchronous)

a|`@CircuitBreaker`
a|`failOn`, `delay`, `delayUnit`, `requestVolumeThreshold`, `failureRatio`, `successThreshold`

a|`@Asynchronous`
a|
|===

You can override annotation parameters via configuration file using property `[classname/methodname/]annotation/parameter`:

[source, properties]
----
org.acme.quickstart.WorldClock/getNow/Retry/maxDuration=30
# Class scope
org.acme.quickstart.WorldClock/Retry/maxDuration=3000
# Global
Retry/maxDuration=3000
----

You can also enable/disable policies using special parameter `enabled`.

[source, properties]
----
org.acme.quickstart.WorldClock/getNow/Retry/enabled=false
# Disable everything except fallback
MP_Fault_Tolerance_NonFallback_Enabled=false
----

TIP: MicroProfile Fault Tolerance integrates with MicroProfile Metrics spec. You can disable it by setting `MP_Fault_Tolerance_Metrics_Enabled` to false.
// end::update_1_2[]

== Observability

*Health Checks*

// tag::update_3_4[]
Quarkus relies on https://github.com/eclipse/microprofile-health[MicroProfile Health, window="_blank"] spec to provide health checks.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-smallrye-health"
----

By just adding this extension, an endpoint is registered to `/health` providing a default health check.

[source, json]
----
{
    "status": "UP",
    "checks": [
    ]
}
----

To create a custom health check you need to implement the `HealthCheck` interface and annotate either with `@Readiness` (ready to process requests) or `@Liveness` (is running) annotations.

[source, java]
----
@Readiness
public class DatabaseHealthCheck implements HealthCheck {
    @Override
    public HealthCheckResponse call() {
        HealthCheckResponseBuilder responseBuilder = 
            HealthCheckResponse.named("Database conn");

        try {
            checkDatabaseConnection();
            responseBuilder.withData("connection", true);
            responseBuilder.up();
        } catch (IOException e) {
            // cannot access the database
            responseBuilder.down()
                    .withData("error", e.getMessage());
        }
        return responseBuilder.build();
    }
}
----

Builds the next output:

[source, json]
----
{
    "status": "UP",
    "checks": [
        {
            "name": "Database conn",
            "status": "UP",
            "data": {
                "connection": true
            }
        }
    ]
}
----

Since health checks are CDI beans, you can do:

[source, java]
----
@ApplicationScoped
public class DatabaseHealthCheck {
    
    @Liveness
    HealthCheck check1() {
      return io.smallrye.health.HealthStatus
                                .up("successful-live");
    }

    @Readiness
    HealthCheck check2() {
      return HealthStatus
                .state("successful-read", this::isReady)
    }

    private boolean isReady() {}
}
----

You can ping liveness or readiness health checks individually by querying `/health/live` or `/health/ready`.

// tag::update_8_14[]
Quarkus comes with some `HealthCheck` implementations for checking service status.

* *SocketHealthCheck*: checks if host is reachable using a socket.
* *UrlHealthCheck*: checks if host is reachable using a Http URL connection.
* *InetAddressHealthCheck*: checks if host is reachable using `InetAddress.isReachable` method.

[source, java]
----
@Liveness
HealthCheck check1() {
    return new UrlHealthCheck("https://www.google.com")
            .name("Google-Check"); 
}
----
// end::update_8_14[]

// tag::update_8_13[]
If you want to override or set manually readiness/liveness probes, you can do it by setting health properties:

[source, properties]
----
quarkus.smallrye-health.root-path=/hello
quarkus.smallrye-health.liveness-path=/customlive
quarkus.smallrye-health.readiness-path=/customready
----
// end::update_8_13[]
// end::update_3_4[]

*Automatic readiness probes*
// tag::update_12_3[]

Some default _readiness probes_ are provided by default if any of the next features are added:

datasource:: A probe to check database connection status.
kafka:: A probe to check kafka connection status. In this case you need to enable manually by setting `quarkus.kafka.health.enabled` to `true`.
mongoDB:: A probe to check MongoDB connection status.
neo4j:: A probe to check Neo4J connection status.
artemis:: A probe to check Artemis JMS connection status.
kafka-streams:: Liveness (for stream state) and Readiness (topics created) probes.
vault:: A probe to check Vault conection status.
gRPC:: A readiness probe for the gRPC services.

You can disable the automatic generation by setting `<component>.health.enabled` to false.

[source, properties]
----
quarkus.kafka-streams.health.enabled=false
quarkus.mongodb.health.enabled=false
quarkus.neo4j.health.enabled=false
----
// end::update_12_3[]

// tag::update_15_8[]
In the case of Vault you can pass parameters to modify the call of the `status` endpoint in Vault.

[source, properties]
----
quarkus.vault.health.enabled=true
quarkus.vault.health.stand-by-ok=true
quarkus.vault.health.performance-stand-by-ok=true
----
// end::update_15_8[]

// tag::update_15_5[]
Health groups are supported to provide custom health checks groups:

[source, java]
----
@io.smallrye.health.HealthGroup("mygroup1")
public class SimpleHealthGroupCheck implements HealthCheck {
}
----

You can ping grouped health checks by querying `/group/mygroup1`.

Group root path can be configured:

[source, properties]
----
quarkus.smallrye-health.group-path=/customgroup
----
// end::update_15_5[]

*Metrics*

Quarkus can utilize the https://github.com/eclipse/microprofile-metrics[MicroProfile Metrics spec, window="_blank"] to provide metrics support.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-smallrye-metrics"
----

The metrics can be read with JSON or the OpenMetrics format.
An endpoint is registered automatically at `/metrics` providing default metrics.

MicroProfile Metrics annotations:

`@Timed`::
Tracks the duration.

// tag::update_15_21[]
`@SimplyTimed`::
Tracks the duration without mean and distribution calculations.
// end::update_15_21[]

`@Metered`::
Tracks the frequency of invocations.

`@Counted`::
Counts number of invocations.

`@Gauge`::
Samples the value of the annotated object.

`@ConcurrentGauge`::
Gauge to count parallel invocations.

`@Metric`::
Used to inject a metric. Valid types `Meter`, `Timer`, `Counter`, `Histogram`. `Gauge` only on producer methods/fields.

[source, java]
----
@GET
//...
@Timed(name = "checksTimer", 
description = "A measure of how long it takes 
                                to perform a hello.", 
unit = MetricUnits.MILLISECONDS)
public String hello() {}

@Counted(name = "countWelcome", 
description = "How many welcome have been performed.")
public String hello() {}
----

`@Gauge` annotation returning a measure as a gauge.

[source, java]
----
@Gauge(name = "hottestSauce", unit = MetricUnits.NONE, 
description = "Hottest Sauce so far.")
public Long hottestSauce() {}
----

Injecting a histogram using `@Metric`.

[source, java]
----
@Inject
@Metric(name = "histogram")
Histogram historgram;
----

// tag::update_14_2[]
You can configure Metrics:

[source, properties]
----
quarkus.smallrye-metrics.path=/mymetrics
----

Prefix is `quarkus.smallrye-metrics`.

`path`::
The path to the metrics handler. (default: `/metrics`)

`extensions.enabled`::
Metrics are enabled or not. (default: `true`)

`micrometer.compatibility`::
Apply Micrometer compatibility mode. (default: `false`)
// end::update_14_2[]

// tag::update_13_12[]
`quarkus.hibernate-orm.metrics.enabled` set to `true` exposes Hibernate metrics under `vendor` scope.
// end::update_13_12[]

// tag::update_14_25[]
`quarkus.mongodb.metrics.enabled` set to `true` exposes MongoDB metrics under `vendor` scope.
// end::update_14_25[]

// tag::update_14_41[]
You can apply metrics annotations via CDI stereotypes:

[source, java]
----
@Stereotype
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.METHOD, ElementType.FIELD })
@Timed(name = "checksTimer", 
description = "A measure of how long it takes 
                                to perform a hello.", 
unit = MetricUnits.MILLISECONDS)
public @interface TimedMilliseconds {
}
----
// end::update_14_41[]

*Tracing*

Quarkus can utilize the https://github.com/eclipse/microprofile-opentracing[MicroProfile OpenTracing, window="_blank"] spec.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="io.quarkus:quarkus-smallrye-opentracing"
----

Requests sent to any endpoint are traced automatically.

This extension includes OpenTracing support and `Jaeger` tracer.

Jaeger tracer configuration:

[source, properties]
----
quarkus.jaeger.service-name=myservice
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.jaeger.endpoint=http://localhost:14268/api/traces
quarkus.jaeger.metrics.enabled=true 
----

`@Traced` annotation can be set to disable tracing at class or method level.

`Tracer` class can be injected into the class.

[source, java]
----
@Inject
Tracer tracer;

tracer.activeSpan().setBaggageItem("key", "value");
----

// tag::update_8_11[]
You can disable `Jaeger` extension by using `quarkus.jaeger.enabled` property.
// end::update_8_11[]

// tag::update_14_40[]
You can log the `traceId`, `spanId` and `sampled` in normal log:

[source, properties]
----
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, 
                                spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
----
// end::update_14_40[]

// tag::update_8_12[]
*Additional tracers*

*JDBC Tracer*

Adds a span for each JDBC queries.

[source, xml]
----
<dependency>
    <groupId>io.opentracing.contrib</groupId>
    <artifactId>opentracing-jdbc</artifactId>
</dependency>
----

Configure JDBC driver apart from tracing properties seen before:

[source, properties]
----
# add ':tracing' to your database URL
quarkus.datasource.url=
    jdbc:tracing:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver=
    io.opentracing.contrib.jdbc.TracingDriver
quarkus.hibernate-orm.dialect=
    org.hibernate.dialect.PostgreSQLDialect
----
// end::update_8_12[]

*AWS XRay*

// tag::update_14_10[]
If you are building native images, and want to use AWS X-Ray Tracing with your lambda you will need to include `quarkus-amazon-lambda-xray` as a dependency in your pom.
// end::update_14_10[]