== Reactive Programming

Quarkus implements https://github.com/eclipse/microprofile-reactive-streams-operators[MicroProfile Reactive spec, window="_blank"] and uses RXJava2 to provide reactive programming model.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-smallrye-reactive-streams-operators"
----

Asynchronous HTTP endpoint is implemented by returning Java `CompletionStage`.
You can create this class either manually or using MicroProfile Reactive Streams spec:

[source, java]
----
@GET
@Path("/reactive")
@Produces(MediaType.TEXT_PLAIN)
public CompletionStage<String> getHello() {
    return ReactiveStreams.of("h", "e", "l", "l", "o")
    .map(String::toUpperCase)
    .toList()
    .run()
    .thenApply(list -> list.toString());
}
----

Creating streams is also easy, you just need to return `Publisher` object.

[source, java]
----
@GET
@Path("/stream")
@Produces(MediaType.SERVER_SENT_EVENTS)
public Publisher<String> publishers() {
        return Flowable
        .interval(500, TimeUnit.MILLISECONDS)
        .map(s -> atomicInteger.getAndIncrement())
        .map(i -> Integer.toString(i));
}
----

*Mutiny and JAX-RS*

// tag::update_14_16[]
Apart from the `CompletionStage` support, there is also support for Mutiny.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-resteasy-mutiny"
----

[source, java]
----
@GET
@Produces(MediaType.TEXT_PLAIN)
public Uni<String> hello() {
    return Uni.createFrom().item(() -> "hello");
}

@GET
@Produces(MediaType.TEXT_PLAIN)
public Multi<String> multi() {
    return Multi.createFrom().items("hello", "world");
}
----
// end::update_14_16[]

*Mutiny*

// tag::update_14_7[]
Quarkus integrates with https://github.com/smallrye/smallrye-mutiny[Mutiny] as reactive programming library:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="mutiny"
----

[source, java]
----
@ApplicationScoped
public static class ReactiveHello {

    public Uni<String> greeting() {
        return Uni.createFrom().item(() -> "hello")
                .emitOn(Infrastructure.getDefaultExecutor());
    }

    public Multi<String> stream() {
        return Multi.createFrom().items("hello", "world")
                .emitOn(Infrastructure.getDefaultExecutor());
    }
}
----

Converting from/to `RxJava2` or `Reactor` APIs:

_RxJava 2_

[source, xml]
----
<dependency>
    <groupId>io.smallrye.reactive</groupId>
    <artifactId>mutiny-rxjava</artifactId>
</dependency>
----

From `RxJava2`:

[source, java]
----
Uni<Void> uniFromCompletable = Uni.createFrom()
                                    .converter(UniRxConverters.fromCompletable(), completable);
Uni<String> uniFromSingle = Uni.createFrom()
                                .converter(UniRxConverters.fromSingle(), single);
Uni<String> uniFromObservable = Uni.createFrom()
                                .converter(UniRxConverters.fromObservable(), observable);
Uni<String> uniFromFlowable = Uni.createFrom()
                                .converter(UniRxConverters.fromFlowable(), flowable);
...

Multi<Void> multiFromCompletable = Multi.createFrom()
                                        .converter(MultiRxConverters.fromCompletable(), completable);
Multi<String> multiFromObservable = Multi.createFrom()
                                        .converter(MultiRxConverters.fromObservable(), observable);
Multi<String> multiFromFlowable = Multi.createFrom()
                                        .converter(MultiRxConverters.fromFlowable(), flowable);
...
----

To `RxJava2`:

[source, java]
----
Completable completable = uni.convert().with(UniRxConverters.toCompletable());
Single<Optional<String>> single = uni.convert().with(UniRxConverters.toSingle());
Observable<String> observable = uni.convert().with(UniRxConverters.toObservable());
Flowable<String> flowable = uni.convert().with(UniRxConverters.toFlowable());
...

Completable completable = multi.convert().with(MultiRxConverters.toCompletable());
Single<Optional<String>> single = multi.convert().with(MultiRxConverters.toSingle());
Observable<String> observable = multi.convert().with(MultiRxConverters.toObservable());
Flowable<String> flowable = multi.convert().with(MultiRxConverters.toFlowable());
...
----

_Reactor API_

[source, xml]
----
<dependency>
    <groupId>io.smallrye.reactive</groupId>
    <artifactId>mutiny-reactor</artifactId>
</dependency>
----

From `Reactor`:

[source, java]
----
Uni<String> uniFromMono = Uni.createFrom().converter(UniReactorConverters.fromMono(), mono);
Uni<String> uniFromFlux = Uni.createFrom().converter(UniReactorConverters.fromFlux(), flux);
Multi<String> multiFromMono = Multi.createFrom().converter(MultiReactorConverters.fromMono(), mono);
Multi<String> multiFromFlux = Multi.createFrom().converter(MultiReactorConverters.fromFlux(), flux);
----

To `Reactor`:

[source, java]
----
Mono<String> mono = uni.convert().with(UniReactorConverters.toMono());
Flux<String> flux = uni.convert().with(UniReactorConverters.toFlux());

Mono<String> mono2 = multi.convert().with(MultiReactorConverters.toMono());
Flux<String> flux2 = multi.convert().with(MultiReactorConverters.toFlux());
----

_CompletionStages_ or _Publisher_

[source, java]
----
CompletableFuture<String> future = Uni
        .createFrom().completionStage(CompletableFuture.supplyAsync(() -> "hello"));

CompletationStage<String> cs = Uni
        .createFrom().subscribeAsCompletionStage();
----

`Multi` implements `Publisher`.
// end::update_14_7[]

== Reactive Messaging
// tag::update_1_4[]
Quarkus relies on MicroProfile https://github.com/eclipse/microprofile-reactive-messaging[Reactive Messaging spec, window="_blank"] to implement reactive messaging streams.

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="
        io.quarkus:quarkus-smallrye-reactive-messaging"
----

You can just start using in-memory streams by using `@Incoming` to produce data and `@Outgoing` to consume data.

Produce every 5 seconds one piece of data.

[source, java]
----
@ApplicationScoped
public class ProducerData {

    @Outgoing("my-in-memory")
    public Flowable<Integer> generate() {
        return Flowable.interval(5, TimeUnit.SECONDS)
                .map(tick -> random.nextInt(100));
    }
}
----

or in Mutiny:

[source, java]
----
@ApplicationScoped
public class ProducerData {
    @Outgoing("my-in-memory")
    public Multi<Integer> generate() {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(5))
                .onItem().apply(n -> random.nextInt(100));
    }
}
----

If you want to dispatch to all subscribers you can annotate the method with `@Broadcast`.

Consumes generated data from `my-in-memory` stream.

[source, java]
----
@ApplicationScoped
public class ConsumerData {
    @Incoming("my-in-memory")
    public void randomNumber(int randomNumber) {
        System.out.println("Received " + randomNumber);
    }
}
----

You can also inject an stream as a field:

[source, java]
----
@Inject
@Stream("my-in-memory") Publisher<Integer> randomRumbers;
----

// tag::update_3_8[]

[source, java]
----
@Inject @Stream("generated-price")
Emitter<String> emitter;
----

*Patterns*

_REST API -> Message_

[source, java]
----
@Inject @Stream(“in”)
Emitter<String> emitter;

emitter.send(message);
----

_Message -> Message_

[source, java]
----
@Incoming(“in”)
@Outgoing(“out”)
public String process(String in) {
}
----

_Message -> SSE_

[source, java]
----
@Inject @Stream(“out”)
Publisher<String> result;

@GET
@Produces(SERVER_SENT_EVENTS)
public Publisher<String> stream() {
    return result;
}
----

_Message -> Business Logic_

[source, java]
----
@ApplicationScoped
public class ReceiverMessages {
    @Incoming("prices")
    public void print(String price) {
    }
}
----

// tag::update_15_22[]
To indicate that the method should be executed on a worker pool you can use `@Blocking`:

[source, java]
----
@Outgoing("Y")
@Incoming("X")
@Blocking
----

To customize:

[source, java]
----
@Blocking(value="my-custom-pool", ordered = false)
----

[source, properties]
----
smallrye.messaging.worker.my-custom-pool.max-concurrency=3
----
// end::update_15_22[]

Possible implementations are:

*In-Memory*

If the stream is not configured then it is assumed to be an in-memory stream, if not then stream type is defined by `connector` field.

*Kafka*

To integrate with Kafka you need to add next extensions:

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="
    io.quarkus:quarkus-smallrye-reactive-messaging-kafka"
----

Then `@Outgoing`, `@Incoming` or `@Stream` can be used.

Kafka configuration schema: `mp.messaging.[outgoing|incoming].\{stream-name\}.<property>=<value>`.

The `connector` type is `smallrye-kafka`.

[source, properties]
----
mp.messaging.outgoing.generated-price.connector=
    smallrye-kafka
mp.messaging.outgoing.generated-price.topic=
    prices
mp.messaging.outgoing.generated-price.bootstrap.servers=
    localhost:9092
mp.messaging.outgoing.generated-price.value.serializer=
    org.apache.kafka.common.serialization.IntegerSerializer

mp.messaging.incoming.prices.connector=
    smallrye-kafka
mp.messaging.incoming.prices.value.deserializer=
    org.apache.kafka.common.serialization.IntegerDeserializer
----

A complete list of supported properties are in Kafka site. For the https://kafka.apache.org/documentation/#producerconfigs[producer, window="_blank"] and for https://kafka.apache.org/documentation/#consumerconfigs[consumer, window="_blank"]

_JSON-B Serializer/Deserializer_

You can use JSON-B to serialize/deserialize objects.

[source, bash]
----
./mvnw quarkus:add-extension 
    -Dextensions="quarkus-kafka-client"
----

To serialize you can use `io.quarkus.kafka.client.serialization.JsonbSerializer`.

To deserialize you need to extend `io.quarkus.kafka.client.serialization.JsonbDeserializer` and provide a type.

[source, java]
----
public class BeerDeserializer 
    extends JsonbDeserializer<Beer> {

    public BeerDeserializer() {
        super(Beer.class);
    }

}
----

*AMQP*

To integrate with AMQP you need to add next extensions:

[source, bash]
----
./mvnw quarkus:add-extension 
    -Dextensions="reactive-messaging-amqp"
----

Then `@Outgoing`, `@Incoming` or `@Stream` can be used.

AMQP configuration schema: `mp.messaging.[outgoing|incoming].\{stream-name\}.<property>=<value>`.
Special properties `amqp-username` and `amqp-password` are used to configure AMQP broker credentials.

The connector type is `smallrye-amqp`.

[source, properties]
----
amqp-username=quarkus
amqp-password=quarkus
# write
mp.messaging.outgoing.generated-price.connector=
    smallrye-amqp
mp.messaging.outgoing.generated-price.address=
    prices
mp.messaging.outgoing.generated-price.durable=
    true
# read
mp.messaging.incoming.prices.connector=
    smallrye-amqp
mp.messaging.incoming.prices.durable=
    true
----

A complete list of supported properties for https://smallrye.io/smallrye-reactive-messaging/#_interacting_using_amqp[AMQP, window="_blank"].

*MQTT*

To integrate with MQTT you need to add next extensions:

[source, bash]
----
./mvnw quarkus:add-extension 
    -Dextensions="vertx, smallrye-reactive-streams-operators
        smallrye-reactive-messaging"
----

And add `io.smallrye.reactive:smallrye-reactive-messaging-mqtt-1.0:0.0.10` dependency in your build tool.

Then `@Outgoing`, `@Incoming` or `@Stream` can be used.

MQTT configuration schema: `mp.messaging.[outgoing|incoming].\{stream-name\}.<property>=<value>`.

The connector type is `smallrye-mqtt`.

[source, properties]
----
mp.messaging.outgoing.topic-price.type=
    smallrye-mqtt
mp.messaging.outgoing.topic-price.topic=
    prices
mp.messaging.outgoing.topic-price.host=
    localhost
mp.messaging.outgoing.topic-price.port=
    1883
mp.messaging.outgoing.topic-price.auto-generated-client-id=
    true

mp.messaging.incoming.prices.type=
    smallrye-mqtt
mp.messaging.incoming.prices.topic=
    prices
mp.messaging.incoming.prices.host=
    localhost
mp.messaging.incoming.prices.port=
    1883
mp.messaging.incoming.prices.auto-generated-client-id=
    true
----
// end::update_3_8[]
// end::update_1_4[]

<<<

== Kafka Streams

// tag::update_3_10[]
Create streaming queries with the Kafka Streams API.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="kafka-streams"
----

// tag::update_7_2[]
All we need to do for that is to declare a CDI producer method which returns the Kafka Streams `org.apache.kafka.streams.Topology`:

[source, java]
----
@ApplicationScoped
public class TopologyProducer {
    @Produces
    public Topology buildTopology() {
        org.apache.kafka.streams.StreamsBuilder.StreamsBuilder 
            builder = new StreamsBuilder();
        // ...
        builder.stream()
            .join()
            // ...
            .toStream()
            .to();
        return builder.build();
    }
}
----

Previous example produces content to another stream.
If you want to write interactive queries, you can use Kafka streams.

[source, java]
----
@Inject
KafkaStreams streams;

return streams
        .store("stream", QueryableStoreTypes.keyValueStore());
----

The Kafka Streams extension is configured via the Quarkus configuration file `application.properties`.

[source, properties]
----
quarkus.kafka-streams.bootstrap-servers=localhost:9092
quarkus.kafka-streams.application-id=temperature-aggregator
quarkus.kafka-streams.application-server=${hostname}:8080
quarkus.kafka-streams.topics=weather-stations,temperature-values

kafka-streams.cache.max.bytes.buffering=10240
kafka-streams.commit.interval.ms=1000
----

*IMPORTANT:* All the properties within the `kafka-streams` namespace are passed through as-is to the Kafka Streams engine. Changing their values requires a rebuild of the application.

// end::update_7_2[]
// end::update_3_10[]

== Reactive PostgreSQL Client

// tag::update_1_8[]
You can use Reactive PostgreSQL to execute queries to PostreSQL database in a reactive way, instead of using JDBC way.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-reactive-pg-client"
----

Database configuration is the same as shown in <<Persistence>> section, but URL is different as it is not a _jdbc_.

[source, properties]
----
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql:///your_database
----

Then you can inject `io.vertx.mutiny.pgclient.PgPool` class.

[source, java]
----
@Inject
PgPool client;

Uni<List<Fruit>> fruits = 
    client.preparedQuery("SELECT * FROM fruits")  
    .onItem().apply(rowSet -> {
        JsonArray jsonArray = new JsonArray();
        for (Row row : rowSet) {
            jsonArray.add(from(row));
        }
        return jsonArray;
    })
----
// end::update_1_8[]

== Reactive MySQL Client

// tag::update_8_8[]
You can use Reactive MySQL to execute queries to MySQL database in a reactive way, instead of using JDBC.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-reactive-mysql-client"
----

Database configuration is the same as shown in <<Persistence>> section, but URL is different as it is not a _jdbc_.

[source, properties]
----
quarkus.datasource.db-kind=mysql
quarkus.datasource.reactive.url=mysql:///your_database
----

Then you can inject `io.vertx.mutiny.mysqlclient.MySQLPool` class.
// end::update_8_8[]

== Reactive DB2 Client

// tag::update_17_3[]
You can use Reactive DB2 to execute queries to DB2 database in a reactive way, instead of using JDBC.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-reactive-db2-client"
----

Database configuration is the same as shown in <<Persistence>> section, but URL is different as it is not a _jdbc_.

[source, properties]
----
quarkus.datasource.db-kind=db2
quarkus.datasource.reactive.url=vertx-reactive:db2://localhost:50005/hreact
----

Then you can inject `io.vertx.mutiny.db2client.DB2Pool` class.
// end::update_17_3[]

== Reactive Transactions

// tag::update_17_9[]
`io.vertx.mutiny.sqlclient.SqlClientHelper` is an util class that allows you to run reactive persisten code within a transaction.

[source, java]
----
Uni<Void> r = SqlClientHelper.inTransactionUni(client, tx -> {
        Uni<RowSet<Row>> insertOne = tx.preparedQuery("INSERT INTO fruits (name) VALUES ($1) RETURNING (id)")
                .execute(Tuple.of(fruit1.name));
});
----
// end::update_17_9[]

== ActiveMQ Artemis

// tag::update_8_4[]
Quarkus uses <<Reactive Messaging>> to integrate with messaging systems, but in case you need deeper control when using https://activemq.apache.org/components/artemis/[Apache ActiveMQ Artemis, window="_blank"] there is also an extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-artemis-core"
----

And then you can inject `org.apache.activemq.artemis.api.core.client.ServerLocator` instance.

[source, java]
----
@ApplicationScoped
public class ArtemisConsumerManager {

    @Inject
    ServerLocator serverLocator;

    private ClientSessionFactory connection;

    @PostConstruct
    public void init() throws Exception {
        connection = serverLocator.createSessionFactory();
    }
}
----

And configure `ServerLocator` in `application.properties`:

[source, properties]
----
quarkus.artemis.url=tcp://localhost:61616
----

You can configure ActiveMQ Artemis in `application.properties` file by using next properties prefixed with `quarkus`:

`artemis.url`::
Connection URL.

`artemis.username`::
Username for authentication.

`artemis.password`::
Password for authentication.

*Artemis JMS*

If you want to use JMS with Artemis, you can do it by using its extension:

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-artemis-jms"
----

And then you can inject `javax.jms.ConnectionFactory`:

[source, java]
----
@ApplicationScoped
public class ArtemisConsumerManager {

    @Inject
    ConnectionFactory connectionFactory;

    private Connection connection;

    @PostConstruct
    public void init() throws JMSException {
        connection = connectionFactory.createConnection();
        connection.start();
    }
}
----

TIP: Configuration options are the same as Artemis core.
// end::update_8_4[]

== Vert.X Reactive Clients

// tag::update_14_33[]

Vert.X Reactive clients in Quarkus, the next clients are supported and you need to add the dependency to use them:

Vert.X Mail Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-mail-client`

Vert.X MongoDB Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-mongo-client`

Vert.X Redis Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-redis-client`

Vert.X Cassandra Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-cassandra-client`

Vert.X Consul Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-consul-client`

Vert.X Kafka Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-kafka-client`

Vert.X AMQP Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-amqp-client`

Vert.X RabbitMQ Client::
`io.smallrye.reactive:smallrye-mutiny-vertx-rabbitmq-client`

Example of Vert.X Web Client:

[source, java]
----
@Inject
Vertx vertx;

private WebClient client;

@PostConstruct
void initialize() {
    this.client = WebClient.create(vertx, ...);
}
----
// end::update_14_33[]

== Amazon SQS Client

// tag::update_16_19[]
[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="amazon-sqs"
----

Injecting the client:

[source, java]
----
@Inject
software.amazon.awssdk.services.sqs.SqsClient sqs;

SendMessageResponse response = sqs.sendMessage(m -> m.queueUrl(queueUrl).messageBody(message));

List<Message> messages = sqs.receiveMessage(m -> m.maxNumberOfMessages(10).queueUrl(queueUrl)).messages();
----

And configure it:

[source,properties]
----
quarkus.sqs.endpoint-override=http://localhost:8010
quarkus.sqs.aws.region=us-east-1
quarkus.sqs.aws.credentials.type=static
quarkus.sqs.aws.credentials.static-provider.access-key-id=test-key
quarkus.sqs.aws.credentials.static-provider.secret-access-key=test-secret
----

You need to set a HTTP client either `URL Connection`:

[source, xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>url-connection-client</artifactId>
</dependency>
----

or Apache HTTP:

[source, xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>apache-client</artifactId>
</dependency>
----

[source, properties]
----
quarkus.sqs.sync-client.type=apache
----

You can go async by using Mutiny:

[source, java]
----
@Inject
software.amazon.awssdk.services.sqs.SqsAsyncClient sqs;

Uni.createFrom()
    .completionStage(
        sqs.sendMessage(m -> m.queueUrl(queueUrl).messageBody(message))
    )
    .onItem()...

return Uni.createFrom()
    .completionStage(
        sqs.receiveMessage(m -> m.maxNumberOfMessages(10).queueUrl(queueUrl))
    )
    .onItem()
----

And you need to add the asynchronous Netty client:

[source, xml]
----
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>netty-nio-client</artifactId>
</dependency>
----

Configuration properties are the same as <<Amazon DynamoDB>> but changing the prefix from `dynamodb` to `sqs`.
// end::update_16_19[]