== RBAC

// tag::update_10_4[]
You can set RBAC using annotations or in `application.properties`.

*Annotations*

You can define roles by using `javax.annotation.security.RolesAllowed` annotation.

[source, java]
----
@RolesAllowed("Subscriber")
----

You can use `io.quarkus.security.Authenticated` as a shortcut of `@RolesAllowed("*")`.

// tag::update_11_2[]
To alter RBAC behaviour there are two configuration properties:

[source, properties]
----
quarkus.security.deny-unannotated=true
----

Configuration options:

`quarkus.jaxrs.deny-uncovered`::
If true denies by default to all JAX-RS endpoints. (default: `false`)

`quarkus.security.deny-unannotated`::
If true denies by default all CDI methods and JAX-RS endpoints. (default: `false`)
// end::update_11_2[]

// tag::update_15_23[]
By default in Quarkus, if an incoming request has a credential the request will always be authenticated (even if the target page does not require authentication).

You can change this behaviour by setting `quarkus.http.auth.proactive` property to `false`.
// end::update_15_23[]

*File Configuration*

Defining RBAC in `application.properties` instead of using annotations.

[source, properties]
----
quarkus.http.auth.policy.role-policy1.roles-allowed=
    user,admin                      
quarkus.http.auth.permission.roles1.paths=
    /roles-secured/*,/other/*,/api/*          
quarkus.http.auth.permission.roles1.policy=
    role-policy1

quarkus.http.auth.permission.permit1.paths=
    /public/*                                
quarkus.http.auth.permission.permit1.policy=
    permit
quarkus.http.auth.permission.permit1.methods=
    GET

quarkus.http.auth.permission.deny1.paths=
    /forbidden                                 
quarkus.http.auth.permission.deny1.policy=
    deny
----

<<<

You need to provide permissions set by using the `roles-allowed` property or use the built-in ones `deny`, `permit` or `authenticated`. 
// end::update_10_4[]

== JWT
// tag::update_1_5[]
Quarkus implements https://github.com/eclipse/microprofile-jwt-auth[MicroProfile JWT RBAC spec, window="_blank"].

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="io.quarkus:quarkus-smallrye-jwt"
----

Minimum JWT required claims: `typ`, `alg`, `kid`, `iss`, `sub`, `exp`, `iat`, `jti`, `upn`, `groups`.

You can inject token by using `JsonWebToken` or a claim individually by using `@Claim`.

[source, java]
----
@Inject
JsonWebToken jwt;

@Inject
@Claim(standard = Claims.preferred_username)
String name;

@Inject
@Claim("groups")
Set<String> groups;

@Inject
JWTParser parser;
----

Set of supported types: `String`, `Set<String>`, `Long`, `Boolean, `javax.json.JsonValue`, `Optional`, `org.eclipse.microprofile.jwt.ClaimValue`.

And configuration in `src/main/resources/application.properties`:

[source, properties]
----
mp.jwt.verify.publickey.location=
    META-INF/resources/publicKey.pem
mp.jwt.verify.issuer=
    https://quarkus.io/using-jwt-rbac
----

Configuration options:

`mp.jwt.verify.publickey`::
Public Key text itself to be supplied as a string.

`mp.jwt.verify.publickey.location`
Relative path or URL of a public key.

`mp.jwt.verify.issuer`::
`iss` accepted as valid.

// tag::update_13_16[]
`smallrye.jwt.token.header`::
Sets header such as `Cookie` is used to pass the token. (default: `Authorization`).

`smallrye.jwt.token.cookie`::
Name of the cookie containing a token.

`smallrye.jwt.token.schemes`::
Comma-separated list containing an alternative single or multiple schemes. (default: `Bearer`).

`smallrye.jwt.require.named-principal`::
A token must have a upn or preferred_username or sub claim set if using `java.security.Principal`. `True` makes throw an exception if not set. (default: `false`).

`smallrye.jwt.path.sub`::
Path to the claim with subject name.

`smallrye.jwt.claims.sub`::
Default sub claim value.

`smallrye.jwt.path.groups`::
Path to the claim containing the groups.

`smallrye.jwt.groups-separator`::
Separator for splitting a string which may contain multiple group values. (default. ` `).

`smallrye.jwt.claims.groups`::
Default groups claim value.

`smallrye.jwt.jwks.refresh-interval`::
JWK cache refresh interval in minutes. (default: `60`).

`smallrye.jwt.expiration.grace`::
Expiration grace in seconds. (default: `60`).

`smallrye.jwt.verify.aud`::
Comma separated list of the audiences that a token aud claim may contain.
// end::update_13_16[]

// tag::update_14_21[]
`smallrye.jwt.verify.algorithm`::
Signature algorith. (defsult: `RS256`)

`smallrye.jwt.token.kid`::
If set then the verification JWK key as well every JWT token must have a matching `kid` header.

`smallrye.jwt.time-to-live`::
The maximum number of seconds that a JWT may be issued for use.
// end::update_14_21[]

// tag::update_16_17[]
`smallrye.jwt.sign.key-location`::
Location of a private key which will be used to sign the claims when either a no-argument `sign()` or `innerSign()` method is called.

`smallrye.jwt.encrypt.key-location`::
Location of a public key which will be used to encrypt the claims or inner JWT when a no-argument `encrypt()` method is called.
// end::update_16_17[]

Supported public key formats:

* PKCS#8 PEM
* JWK
* JWKS
* JWK Base64 URL
* JWKS Base64 URL

To send a token to server-side you should use `Authorization` header: `curl -H "Authorization: Bearer eyJraWQiOi..."`.

To inject claim values, the bean must be `@RequestScoped` CDI scoped.
If you need to inject claim values in scope with a lifetime greater than `@RequestScoped` then you need to use `javax.enterprise.inject.Instance` interface.

[source, java]
----
@Inject
@Claim(standard = Claims.iat)
private Instance<Long> providerIAT;
----

*RBAC*

JWT `groups` claim is directly mapped to roles to be used in security annotations.

[source, java]
----
@RolesAllowed("Subscriber")
----
// end::update_1_5[]

*Generate tokens*

// tag::update_13_15[]
JWT generation API:

[source, java]
----
Jwt.claims()
    .issuer("https://server.com")
    .claim("customClaim", 3)
    .sign(createKey());

JwtSignatureBuilder jwtSignatureBuilder = Jwt.claims("/testJsonToken.json").jws();
jwtSignatureBuilder
     .signatureKeyId("some-key-id")
     .signatureAlgorithm(SignatureAlgorithm.ES256)
     .header("custom-header", "custom-value");    
     .sign(createKey());

Jwt.claims("/testJsonToken.json")
    .encrypt(createKey());

JwtEncryptionBuilder jwtEncryptionBuilder = Jwt.claims("/testJsonToken.json").jwe();
jwtEncryptionBuilder
     .keyEncryptionKeyId("some-key-id")
      .keyEncryptionAlgorithm(KeyEncryptionAlgorithm.ECDH_ES_A256KW)
     .header("custom-header", "custom-value");
     .encrypt(createKey());

Jwt.claims("/testJsonToken.json")
  .innerSign(createKey());
  .encrypt(createKey());
----
// end::update_13_15[]

== OpenId Connect
// tag::update_1_9[]
Quarkus can use OpenId Connect or OAuth 2.0 authorization servers such as  https://www.keycloak.org/[Keycloak, window="_blank"] to protect resources using bearer token issued by Keycloak server.

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="using-openid-connect"
----

You can also protect resources with security annotations.

[source, java]
----
@GET
@RolesAllowed("admin")
----

Configure application to Keycloak service in `application.properties` file.

[source, properties]
----
quarkus.oidc.realm=quarkus
quarkus.oidc.auth-server-url=http://localhost:8180/auth
quarkus.oidc.resource=backend-service
quarkus.oidc.bearer-only=true
quarkus.oidc.credentials.secret=secret
----

// tag::update_14_39[]
Configuration options with `quarkus.oidc` prefix:

`enabled`::
The OIDC is enabled. (default: `true`)

`tenant-enabled`::
If the tenant configuration is enabled. (default: `true`)

`application-type`::
The application type. Possible values: `web_app`, `service`. (default: `service`)

`connection-delay`::
The maximum amount of time the adapter will try connecting.

`auth-server-url`::
The base URL of the OpenID Connect (OIDC) server.

`introspection-path`::
Relative path of the RFC7662 introspection service.

`jwks-path`::
Relative path of the OIDC service returning a JWK set.

`public-key`::
Public key for the local JWT token verification

`client-id`::
The client-id of the application.

`roles.role-claim-path`::
Path to the claim containing an array of groups. (`realm/groups`)

`roles.role-claim-separator`::
Separator for splitting a string which may contain multiple group values.

`token.issuer`::
Issuer claim value.

`token.audience`::
Audience claim value.

`token.expiration-grace`::
Expiration grace period in seconds.

`token.principal-claim`::
Name of the claim which contains a principal name.

// tag::update_16_3[]
`token.refresh-expired`::
If property is enabled then a refresh token request is performed.
// end::update_16_3[]

`credentials.secret`::
The client secret

`authentication.redirect-path`::
Relative path for calculating a `redirect_uri` query parameter.

`authentication.restore-path-after-redirect`::
The original request URI used before the authentication will be restored after the user has been redirected back to the application. (default: `true`)

`authentication.scopes`::
List of scopes.

`authentication.extra-params`::
Additional properties which will be added as the query parameters .

`authentication.cookie-path`::
Cookie path parameter.
// end::update_14_39[]

// tag::update_15_9[]
`proxy.host`::
The host (name or IP address) of the Proxy.

`proxy.port`::
The port number of the Proxy. (default: `80`)

`proxy.username`::
The username to authenticate.

`proxy.password`::
The password to authenticate.
// end::update_15_9[]

// tag::update_16_3[]
`end-session-path`::
Relative path of the OIDC `end_session_endpoint`.

`logout.path`::
The relative path of the logout endpoint at the application.

`logout.post-logout-path`::
Relative path of the application endpoint where the user should be redirected to after logging out.
// end::update_16_3[]

NOTE:  With Keycloak OIDC server `https://host:port/auth/realms/{realm}` where `{realm}` has to be replaced by the name of the Keycloak realm.

TIP: You can use `quarkus.http.cors` property to enable consuming form different domain.
// end::update_1_9[]

*Multi-tenancy* 

// tag::update_14_34[]
Multi-tenancy is supported by adding a sub-category to OIDC configuration properties (ie `quarkus.oidc.{tenent_id}.property`).

[source, properties]
----
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/quarkus
quarkus.oidc.client-id=multi-tenant-client
quarkus.oidc.application-type=web-app

quarkus.oidc.tenant-b.auth-server-url=https://accounts.google.com
quarkus.oidc.tenant-b.application-type=web-app
quarkus.oidc.tenant-b.client-id=xxxx
quarkus.oidc.tenant-b.credentials.secret=yyyy
quarkus.oidc.tenant-b.token.issuer=https://accounts.google.com
quarkus.oidc.tenant-b.authentication.scopes=email,profile,openid
----
// end::update_14_34[]

== OAuth2
// tag::update_6_8[]
Quarkus integrates with OAuth2 to be used in case of opaque tokens (none JWT) and its validation against an introspection endpoint.

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="security-oauth2"
----

And configuration in `src/main/resources/application.properties`:

[source, properties]
----
quarkus.oauth2.client-id=client_id
quarkus.oauth2.client-secret=secret
quarkus.oauth2.introspection-url=http://oauth-server/introspect
----

And you can map roles to be used in security annotations.

[source, java]
----
@RolesAllowed("Subscriber")
----

Configuration options:

`quarkus.oauth2.enabled`::
Determine if the OAuth2 extension is enabled. (default: `true`)

`quarkus.oauth2.client-id`::
The OAuth2 client id used to validate the token.

`quarkus.oauth2.client-secret`::
The OAuth2 client secret used to validate the token.

`quarkus.oauth2.introspection-url`::
URL used to validate the token and gather the authentication claims.

`quarkus.oauth2.role-claim`::
The claim that is used in the endpoint response to load the roles ((default: `scope`)
// end::update_6_8[]

== Authenticating via HTTP

// tag::update_10_3[]
HTTP basic auth is enabled by the `quarkus.http.auth.basic=true` property.
// end::update_10_3[]

// tag::update_11_1[]
HTTP form auth is enabled by the `quarkus.http.auth.form.enabled=true` property.
// end::update_11_1[]

Then you need to add `elytron-security-properties-file` or `elytron-security-jdbc`.

== Security with Properties File

// tag::update_10_2[]
You can also protect endpoints and store identities (user, roles) in the file system.

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="elytron-security-properties-file"
----

You need to configure the extension with users and roles files:

And configuration in `src/main/resources/application.properties`:

[source, properties]
----
quarkus.security.users.file.enabled=true
quarkus.security.users.file.users=test-users.properties
quarkus.security.users.file.roles=test-roles.properties
quarkus.security.users.file.auth-mechanism=BASIC
quarkus.security.users.file.realm-name=MyRealm
quarkus.security.users.file.plain-text=true
----

Then `users.properties` and `roles.properties`:

[source, properties]
----
scott=jb0ss 
jdoe=p4ssw0rd
----

[source, properties]
----
scott=Admin,admin,Tester,user 
jdoe=NoRolesUser
----

*IMPORTANT:*  If `plain-text` is set to `false` (or omitted) then passwords must be stored in the form MD5 (`username`:`realm`:`password`).

Elytron File Properties configuration properties.
Prefix `quarkus.security.users` is skipped.

`file.enabled`::
The file realm is enabled. (default: `false`)

`file.auth-mechanism`::
The authentication mechanism. ( default: `BASIC`)

`file.realm-name`::
The authentication realm name. (default: `Quarkus`)

`file.plain-text`::
If passwords are in plain or in MD5. (default: `false`)

`file.users`::
Classpath resource of user/password. (default: `users.properties`)

`file.roles`::
Classpath resource of user/role. (default: `roles.properties`)

*Embedded Realm*

You can embed user/password/role in the same `application.properties`:

[source, properties]
----
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.scott=jb0ss
quarkus.security.users.embedded.roles.scott=admin,tester,user
quarkus.security.users.embedded.auth-mechanism=BASIC
----

*IMPORTANT:*  If plain-text is set to `false` (or omitted) then passwords must be stored in the form MD5 (`username`:`realm`:`password`).

Prefix `quarkus.security.users.embedded` is skipped.

`file.enabled`::
The file realm is enabled. (default: `false`)

`file.auth-mechanism`::
The authentication mechanism. (default: `BASIC`)

`file.realm-name`::
The authentication realm name. (default: `Quarkus`)

`file.plain-text`::
If passwords are in plain or in MD5. (default: `false`)

`file.users.*`::
`*` is user and value is password.

`file.roles.*`::
`*` is user and value is role.
// end::update_10_2[]

== Security with a JDBC Realm

// tag::update_9_7[]
You can also protect endpoints and store identities in a database.

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="elytron-security-jdbc"
----

You still need to add the database driver (ie `jdbc-h2`).

You need to configure JDBC and Elytron JDBC Realm:

[source, properties]
----
quarkus.datasource.url=
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=sa
quarkus.datasource.password=sa

quarkus.security.jdbc.enabled=true
quarkus.security.jdbc.principal-query.sql=
    SELECT u.password, u.role FROM test_user u WHERE u.user=? 
quarkus.security.jdbc.principal-query
    .clear-password-mapper.enabled=true 
quarkus.security.jdbc.principal-query
    .clear-password-mapper.password-index=1
quarkus.security.jdbc.principal-query
    .attribute-mappings.0.index=2 
quarkus.security.jdbc.principal-query
    .attribute-mappings.0.to=groups
----

You need to set the index (1-based) of password and role.

Elytron JDBC Realm configuration properties.
Prefix `quarkus.security.jdbc` is skipped.

`auth-mechanism`::
The authentication mechanism. (default: `BASIC`)

`realm-name`::
The authentication realm name. (default: `Quarkus`)

`enabled`::
If the properties store is enabled. (default: `false`)

`principal-query.sql`::
The sql query to find the password.

`principal-query.datasource`::
The data source to use.

`principal-query.clear-password-mapper.enabled`::
If the clear-password-mapper is enabled. (default: `false`)

`principal-query.clear-password-mapper.password-index`::
The index of column containing clear password. (default: `1`)

`principal-query.bcrypt-password-mapper.enabled`::
If the bcrypt-password-mapper is enabled. (default: `false`)

`principal-query.bcrypt-password-mapper.password-index`::
The index of column containing password hash. (default: `0`)

`principal-query.bcrypt-password-mapper.hash-encoding`::
A string referencing the password hash encoding (`BASE64` or `HEX`). (default: `BASE64`)

`principal-query.bcrypt-password-mapper.salt-index`::
The index column containing the Bcrypt salt. (default: `0`)

`principal-query.bcrypt-password-mapper.salt-encoding`::
A string referencing the salt encoding (`BASE64` or `HEX`). (default: `BASE64`)

`principal-query.bcrypt-password-mapper.iteration-count-index`::
The index column containing the Bcrypt iteration count. (default: `0`)

For multiple datasources you can use the datasource name in the properties:

[source, properties]
----
quarkus.datasource.url=
quarkus.security.jdbc.principal-query.sql=

quarkus.datasource.permissions.url=
quarkus.security.jdbc.principal-query.permissions.sql=
----
// end::update_9_7[]

== Security with JPA

// tag::update_14_8[]
You can also protect endpoints and store identities in a database using JPA.

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="security-jpa"
----

NOTE: Also you might require `jdbc-postgresql`, `resteasy`, `hibernate-orm-panache`.

[source, java]
----
@io.quarkus.security.jpa.UserDefinition
@Table(name = "test_user")
@Entity
public class User extends PanacheEntity {
    @io.quarkus.security.Username
    public String name;

    @io.quarkus.security.Password
    public String pass;

    @ManyToMany
    @Roles
    public List<Role> roles = new ArrayList<>();

    public static void add(String username, String password) {
        User user = new User();
        user.username = username;
        user.password = BcryptUtil.bcryptHash(password);
        user.persist();
    }
}

@Entity
public class Role extends PanacheEntity {

    @ManyToMany(mappedBy = "roles")
    public List<ExternalRolesUserEntity> users;

    @io.quarkus.security.RolesValue
    public String role;
}
----

You need to configure JDBC:

[source, properties]
----
quarkus.datasource.url=jdbc:postgresql:security_jpa
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus

quarkus.hibernate-orm.database.generation=drop-and-create
----
// end::update_14_8[]

== Security with LDAP

// tag::update_15_20[]
You can also protect endpoints and store identities in a database using LDAP.

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="elytron-security-ldap"
----

[source, properties]
----
quarkus.security.ldap.enabled=true
quarkus.security.ldap.dir-context.principal=uid=tool,ou=accounts,o=YourCompany,c=DE
quarkus.security.ldap.dir-context.url=ldaps://ldap.server.local
quarkus.security.ldap.dir-context.password=PASSWORD
quarkus.security.ldap.identity-mapping.rdn-identifier=uid
quarkus.security.ldap.identity-mapping.search-base-dn=ou=users,ou=tool,o=YourCompany,c=DE
quarkus.security.ldap.identity-mapping.attribute-mappings."0".from=cn
quarkus.security.ldap.identity-mapping.attribute-mappings."0".to=groups
quarkus.security.ldap.identity-mapping.attribute-mappings."0".filter=(member=uid={0})
quarkus.security.ldap.identity-mapping.attribute-mappings."0".filter-base-dn=ou=roles,ou=tool,o=YourCompany,c=DE
----

*Testing*

There is a Quarkus Test Resource that starts and stops InMemory LDAP server before and after test suite.
It is running in `localhost` with `dc=quarkus,dc=io` and binding credentials (`"uid=admin,ou=system", "secret"`).
Imports _LDIF_ from a file located at root of the classpath named `quarkus-io.ldif`.

Register dependency io.quarkus:quarkus-test-ldap:test.

And annotate the test:

[source, java]
----
@QuarkusTestResource(io.quarkus.test.ldap.LdapServerTestResource.class)
public class ElytronLdapExtensionTestResources {
}
----

Elytron LDAP Realm configuration properties.
Prefix `quarkus.security.ldap` is skipped.

`enabled`::
Enable the LDAP elytron module (default: `false`)

`realm-name`::
The elytron realm name (default: `Quarkus`)

`direct-verification`::
Provided credentials are verified against LDAP (default: `true`)

`dir-context.url`::
The url of the LDAP server.

`dir-context.principal`::
User (`bindDn`) which is used to connect to LDAP server.

`dir-context.password`::
The password (`bindCredential`) which belongs to the principal.

`identity-mapping.rdn-identifier`::
The identifier (`baseFilter`) which correlates to the provided user (default: `uid`)

`identity-mapping.search-base-dn`::
The dn where we look for users.

`identity-mapping.attribute-mappings.<id>.from`::
The `roleAttributeId` from which is mapped

`identity-mapping.attribute-mappings.<id>.to`::
The identifier whom the attribute is mapped to (default: `gropus`)

`identity-mapping.attribute-mappings.<id>.filter`::
The filter (`roleFilter`)

`identity-mapping.attribute-mappings.<id>.filter-base-dn`::
The filter base dn (`rolesContextDn`)
// end::update_15_20[]

== Vault

// tag::update_10_5[]
Quarkus integrates with https://www.vaultproject.io/[Vault] to manage secrets or protecting sensitive data. 

[source, bash]
----
mvn quarkus:add-extension 
    -Dextensions="vault"
----

And configuring Vault in `application.properties`:

[source, properties]
----
# vault url
quarkus.vault.url=http://localhost:8200

quarkus.vault.authentication.userpass.username=
    bob
quarkus.vault.authentication.userpass.password=
    sinclair

# path within the kv secret engine
quarkus.vault.secret-config-kv-path=
    myapps/vault-quickstart/config
quarkus.vault.secret-config-kv-path.singer=
    multi/singer
----

`vault kv put secret/myapps/vault-quickstart/config a-private-key=123456`

`vault kv put secret/multi/singer firstname=paul`

[source, java]
----
@ConfigProperty(name = "a-private-key")
String privateKey;

@ConfigProperty(name = "singer.firstname")
String firstName;
----

You can access the KV engine programmatically:

[source, java]
----
@Inject
VaultKVSecretEngine kvSecretEngine;

kvSecretEngine.readSecret("myapps/vault-quickstart/" + vaultPath).toString();

Map<String, String> secrets;
kvSecretEngine.writeSecret("myapps/vault-quickstart/crud", secrets);

kvSecretEngine.deleteSecret("myapps/vault-quickstart/crud");
----

*Fetching credentials DB*

With the next _kv_ `vault kv put secret/myapps/vault-quickstart/db password=connor`

[source, properties]
----
quarkus.vault.credentials-provider.mydatabase.kv-path=
    myapps/vault-quickstart/db
quarkus.datasource.credentials-provider=
    mydatabase

quarkus.datasource.url= 
    jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver= 
    org.postgresql.Driver
quarkus.datasource.username=
    sarah
----

No password is set as it is fetched from Vault.

INFO: https://www.vaultproject.io/docs/secrets/databases/index.html[dynamic database credentials] through the `database-credentials-role` property.

*Transit*

// tag::update_13_14[]
[source, java]
----
@Inject
VaultTransitSecretEngine transit;

transit.encrypt("my_encryption", text);
transit.decrypt("my_encryption", text).asString();
transit.sign("my-sign-key", text);
----
// end::update_13_14[]

*Vault TOTP*

// tag::update_15_17[]
TOTP secret engine is supported by using `io.quarkus.vault.VaultTOTPSecretEngine` class:

[source, java]
----
@Inject
VaultTOTPSecretEngine vaultTOTPSecretEngine;

CreateKeyParameters createKeyParameters = new CreateKeyParameters("Google", "test@gmail.com");
createKeyParameters.setPeriod("30m");

/** Generate Key (QR code) */
final Optional<KeyDefinition> myKey = vaultTOTPSecretEngine
                                            .createKey("my_key_2", createKeyParameters);

/** Generate key number to login */
final String keyCode = vaultTOTPSecretEngine.generateCode("my_key_2");

/** Login logic */
boolean valid = vaultTOTPSecretEngine.validateCode("my_key_2", keyCode);
----
// end::update_15_17[]

Vault configuration properties.
Prefix `quarkus.vault` is skipped.

`url`::
Vault server URL

`authentication.client-token`::
Vault token to access

`authentication.app-role.role-id`::
Role Id for AppRole auth

`authentication.app-role.secret-id`::
Secret Id for AppRole auth

// tag::update_15_19[]
`authentication.app-role.secret-id-wrapping-token`::
Wrapping token containing a Secret Id. `secret-id` and `secret-id-wrapping-token` are exclusive.
// end::update_15_19[]

`authentication.userpass.username`::
Username for userpass auth

`authentication.userpass.password`::
Password for userpass auth

// tag::update_15_19[]
`authentication.userpass.password-wrapping-token`::
Wrapping token containing a password. `password` and `password-wrapping-token` are exclusive.
// end::update_15_19[]

`authentication.kubernetes.role`::
Kubernetes authentication role

`authentication.kubernetes.jwt-token-path`::
Location of the file containing the Kubernetes JWT token

`renew-grace-period`::
Renew grace period duration (default: `1H`)

`secret-config-cache-period`::
Vault config source cache period (default: `10M`)

`secret-config-kv-path`::
Vault path in kv store. List of paths is supported in CSV

`log-confidentiality-level`::
Used to hide confidential infos. `low`, `medium`, `high` (default: `medium`)

`kv-secret-engine-version`::
Kv secret engine version (default: 1)

`kv-secret-engine-mount-path`
Kv secret engine path (default: `secret`)

`tls.skip-verify`::
Allows to bypass certificate validation on TLS communications (default: `false`)

`tls.ca-cert`::
Certificate bundle used to validate TLS communications

`tls.use-kubernetes-ca-cert`::
TLS will be active (default: `true`)

`connect-timeout`::
Tiemout to establish a connection (default: `5S`)

`read-timeout`::
Request timeout (default: `1S`)

`credentials-provider."credentials-provider".database-credentials-role`::
Database credentials role

`credentials-provider."credentials-provider".kv-path`::
A path in vault kv store, where we will find the kv-key

`credentials-provider."credentials-provider".kv-key`::
Key name to search in vault path kv-path (default: `password`)
// end::update_10_5[]