== Spring DI
// tag::update_7_5[]

Quarkus provides a compatibility layer for Spring dependency injection.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-spring-di"
----

Some examples of what you can do.
Notice that annotations are the Spring original ones.

[soure, java]
----
@Configuration
public class AppConfiguration {

    @Bean(name = "capitalizeFunction")
    public StringFunction capitalizer() {
        return String::toUpperCase;
    }
}
----

Or as a component:

[source, java]
----
@Component("noopFunction")
public class NoOpSingleStringFunction 
    implements StringFunction {
}
----

Also as a service and injection properties from `application.properties`.

[source, java]
----
@Service
public class MessageProducer {

    @Value("${greeting.message}")
    String message;

}
----

And you can inject using `Autowired` or constructor in a component and in a JAX-RS resource too.

[source, java]
----
@Component
public class GreeterBean {

    private final MessageProducer messageProducer;

    @Autowired @Qualifier("noopFunction")
    StringFunction noopStringFunction;

    public GreeterBean(MessageProducer messageProducer) {
        this.messageProducer = messageProducer;
    }
}
----
// end::update_7_5[]

<<<

== Spring Boot Configuration
// tag::update_13_3[]

Quarkus provides a compatibility layer for Spring Boot `ConfigurationProperties`.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-spring-boot-properties"
----

[source, java]
----
@ConfigurationProperties("example")
public final class ClassProperties {

    private String value;
    private AnotherClass anotherClass;

    // getters/setters
}
----

[source, properties]
----
example.value=class-value
example.anotherClass.value=true
----
// end::update_13_3[]

== Spring Cloud Config Client

// tag::update_14_11[]
Quarkus integrates https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_client.html[Spring Cloud Config Client] and MicroProfile Config spec.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-spring-cloud-config-client"
----

You need to configure the extension:

[source, properties]
----
quarkus.spring-cloud-config.uri=http://localhost:8089
quarkus.spring-cloud-config.username=user
quarkus.spring-cloud-config.password=pass
quarkus.spring-cloud-config.enabled=true
----

[source, java]
----
@ConfigProperty(name = "greeting.message")
String greeting;
----

Prefix is `quarkus.spring-cloud-config`.

`uri`::
Base URI where the Spring Cloud Config Server is available. (default: `localhost:8888`)

`username`::
Username to be used if the Config Server has BASIC Auth enabled.

`password`::
Password to be used if the Config Server has BASIC Auth enabled.

`enabled`::
Enables read configuration from Spring Cloud Config Server. (default: `false`)

`fail-fast`::
True to not start application if cannot access to the server. (default: `false`)

`connection-timeout`::
The amount of time to wait when initially establishing a connection before giving up and timing out. (default: `10S`)

`read-timeout`::
The amount of time to wait for a read on a socket before an exception is thrown. (default: `60S`)
// end::update_14_11[]

== Spring Web
// tag::update_7_6[]

Quarkus provides a compatibility layer for Spring Web.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-spring-web"
----

Specifically supports the REST related features.
Notice that infrastructure things like `BeanPostProcessor` will not be executed.

[source, java]
----
@RestController
@RequestMapping("/greeting")
public class GreetingController {

    private final GreetingBean greetingBean;

    public GreetingController(GreetingBean greetingBean) {
        this.greetingBean = greetingBean;
    }

    @GetMapping("/{name}")
    public Greeting hello(@PathVariable(name = "name") 
                            String name) {
        return new Greeting(greetingBean.greet(name));
    }
}
----

Supported annotations are: `RestController`, `RequestMapping`, `GetMapping`, `PostMapping`, `PutMapping`, `DeleteMapping`, `PatchMapping`, `RequestParam`, `RequestHeader`, `MatrixVariable`, `PathVariable`, `CookieValue`, `RequestBody`, `ResponseStatus`, `ExceptionHandler` and `RestControllerAdvice`.
// end::update_7_6[]

// tag::update_8_5[]
TIP: If you scaffold the project with `spring-web` extension, then Spring Web annotations are sed in the generated project. `mvn io.quarkus:quarkus-maven-plugin:{version}:create ... -Dextensions="spring-web"`.
// end::update_8_5[]

// tag::update_11_7[]
The next return types are supported: `org.springframework.http.ResponseEntity` and `java.util.Map`.

The next parameter types are supported: An `Exception` argument and `ServletRequest`/`HttpServletRequest` (adding `quarkus-undertow` dependency).
// end::update_11_7[]

== Spring Data JPA
// tag::update_8_2[]

While users are encouraged to use Hibernate ORM with Panache for Relational Database access, Quarkus provides a compatibility layer for https://docs.spring.io/spring-data/jpa/docs/current/reference/html/[Spring Data JPA, window="_blank" ] repositories.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="quarkus-spring-data-jpa"
----

INFO: Of course you still need to add the JDBC driver, and configure it in `application.properties`.

[source, java]
----
public interface FruitRepository 
        extends CrudRepository<Fruit, Long> {
    List<Fruit> findByColor(String color);
}
----

And then you can inject it either as shown in <<Spring DI>> or in <<Spring Web>>.

Interfaces supported: 

* `org.springframework.data.repository.Repository` 
* `org.springframework.data.repository.CrudRepository` 
* `org.springframework.data.repository.PagingAndSortingRepository`
* `org.springframework.data.jpa.repository.JpaRepository`.

INFO: Generated repositories are automatically annotated with `@Transactional`.

Repository fragments is also supported:

[source, java]
----
public interface PersonRepository 
    extends JpaRepository<Person, Long>, PersonFragment {
    
    void makeNameUpperCase(Person person); 
}
----

User defined queries:

[source, java]
----
@Query("select m from Movie m where m.rating = ?1")
Iterator<Movie> findByRating(String rating);

@Modifying
@Query("delete from Movie where rating = :rating")
void deleteByRating(@Param("rating") String rating);

@Query(value = "SELECT COUNT(*), publicationYear FROM Book GROUP BY publicationYear")
List<BookCountByYear> findAllByPublicationYear2();

interface BookCountByYear {
    int getPublicationYear();

    Long getCount();
}
----

What is currently unsupported:

* Methods of `org.springframework.data.repository.query.QueryByExampleExecutor`
* QueryDSL support
* Customizing the base repository
* `java.util.concurrent.Future` as return type
* Native and named queries when using `@Query`
// end::update_8_2[]

== Spring Security
// tag::update_12_11[]
Quarkus provides a compatibility layer for https://spring.io/projects/spring-security[Spring Security, window="_blank" ].

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="spring-security"
----

You need to choose a security extension to define user, roles, ... such as `openid-connect`, `oauth2`, `properties-file` or `security-jdbc` as seen at <<RBAC>>.

Then you can use Spring Security annotations to protect the methods:

[source, java]
----
@Secured("admin")
@GetMapping
public String hello() {
    return "hello";
}
----

Quarkus provides support for some of the most used features of Spring Security’s `@PreAuthorize` annotation.

Some examples:

*hasRole*

* `@PreAuthorize("hasRole('admin')")` 
* `@PreAuthorize("hasRole(@roles.USER)")` where `roles` is a bean defined with `@Component` annotation and `USER` is a public field of the class.

*hasAnyRole*

* `@PreAuthorize("hasAnyRole(@roles.USER, 'view')")`

*Permit and Deny All*

* `@PreAuthorize("permitAll()")`
* `@PreAuthorize("denyAll()")`

*Anonymous and Authenticated*

* `@PreAuthorize("isAnonymous()")`
* `@PreAuthorize("isAuthenticated()")`

*Expressions*

* Checks if the current logged in user is the same as the username method parameter:

[source, java]
----
@PreAuthorize("#person.name == authentication.principal.username")
public void doSomethingElse(Person person){}
----

* Checks if calling a method if user can access:

[source, java]
----
@PreAuthorize("@personChecker.check(#person, authentication.principal.username)")
public void doSomething(Person person){}

@Component
public class PersonChecker {
    public boolean check(Person person, String username) {
        return person.getName().equals(username);
    }
}
----

* Combining expressions:

[source, java]
----
@PreAuthorize("hasAnyRole('user', 'admin') AND #user == principal.username")
public void allowedForUser(String user) {}
----
// end::update_12_11[]

== Spring Cache

// tag::update_16_7[]
Quarkus provides a compatibility layer for Spring dependency injection.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="spring-cache"
----

[source, java]
----
@org.springframework.cache.annotation.Cacheable("someCache")
public Greeting greet(String name) {}
----

Quarkus provides compatibility with the following Spring Cache annotations:

* `@Cacheable`
* `@CachePut`
* `@CacheEvict`
// end::update_16_7[]

== Spring Schedule

// tag::update_17_13[]
Quarkus provides a compatibility layer for Spring Scheduled annotation.

[source, bash]
----
./mvnw quarkus:add-extension 
  -Dextensions="spring-scheduled"
----

[source, java]
----
@org.springframework.scheduling.annotation.Scheduled(cron="*/5 * * * * ?")   
void cronJob() {
    System.out.println("Cron expression hardcoded");
}

@Scheduled(fixedRate = 1000) 
@Scheduled(cron = "{cron.expr}") 
----
// end::update_17_13[]